// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog_crawl_queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const advanceCatalogCrawl = `-- name: AdvanceCatalogCrawl :exec
UPDATE catalog_crawls SET next_page_index = $1,
    entries_seen = entries_seen + $2,
    entries_added = entries_added + $3,
    entries_updated = entries_updated + $4,
    locked_at = NOW(), updated_at = NOW()
WHERE id = $5 AND status = 'running'
`

type AdvanceCatalogCrawlParams struct {
	NextPageIndex  int32       `db:"next_page_index" json:"NextPageIndex"`
	EntriesSeen    int64       `db:"entries_seen" json:"EntriesSeen"`
	EntriesAdded   int64       `db:"entries_added" json:"EntriesAdded"`
	EntriesUpdated int64       `db:"entries_updated" json:"EntriesUpdated"`
	ID             pgtype.UUID `db:"id" json:"ID"`
}

// AdvanceCatalogCrawl
//
//	UPDATE catalog_crawls SET next_page_index = $1,
//	    entries_seen = entries_seen + $2,
//	    entries_added = entries_added + $3,
//	    entries_updated = entries_updated + $4,
//	    locked_at = NOW(), updated_at = NOW()
//	WHERE id = $5 AND status = 'running'
func (q *Queries) AdvanceCatalogCrawl(ctx context.Context, arg *AdvanceCatalogCrawlParams) error {
	_, err := q.db.Exec(ctx, advanceCatalogCrawl,
		arg.NextPageIndex,
		arg.EntriesSeen,
		arg.EntriesAdded,
		arg.EntriesUpdated,
		arg.ID,
	)
	return err
}

const claimCatalogCrawl = `-- name: ClaimCatalogCrawl :one
UPDATE catalog_crawls SET status = 'running', locked_at = NOW(), locked_by = $1,
    attempts = attempts + 1, updated_at = NOW()
WHERE id = (
    SELECT c.id FROM catalog_crawls c
    WHERE c.status IN ('queued', 'retry_wait')
      AND (c.retry_at IS NULL OR c.retry_at <= NOW())
      AND NOT EXISTS (
        SELECT 1 FROM catalog_crawls active
        WHERE active.platform = c.platform AND active.status = 'running'
          AND active.locked_at > NOW() - INTERVAL '15 minutes'
      )
    ORDER BY c.created_at
    LIMIT 1 FOR UPDATE SKIP LOCKED
)
RETURNING id, created_at, updated_at, channel_id, requested_by, feed_url, feed_kind, platform, next_page_index, page_size, overlap_size, status, attempts, retry_at, entries_seen, entries_added, entries_updated, last_error, refresh, locked_at, locked_by, finished_at
`

// ClaimCatalogCrawl
//
//	UPDATE catalog_crawls SET status = 'running', locked_at = NOW(), locked_by = $1,
//	    attempts = attempts + 1, updated_at = NOW()
//	WHERE id = (
//	    SELECT c.id FROM catalog_crawls c
//	    WHERE c.status IN ('queued', 'retry_wait')
//	      AND (c.retry_at IS NULL OR c.retry_at <= NOW())
//	      AND NOT EXISTS (
//	        SELECT 1 FROM catalog_crawls active
//	        WHERE active.platform = c.platform AND active.status = 'running'
//	          AND active.locked_at > NOW() - INTERVAL '15 minutes'
//	      )
//	    ORDER BY c.created_at
//	    LIMIT 1 FOR UPDATE SKIP LOCKED
//	)
//	RETURNING id, created_at, updated_at, channel_id, requested_by, feed_url, feed_kind, platform, next_page_index, page_size, overlap_size, status, attempts, retry_at, entries_seen, entries_added, entries_updated, last_error, refresh, locked_at, locked_by, finished_at
func (q *Queries) ClaimCatalogCrawl(ctx context.Context, workerID string) (*CatalogCrawl, error) {
	row := q.db.QueryRow(ctx, claimCatalogCrawl, workerID)
	var i CatalogCrawl
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ChannelID,
		&i.RequestedBy,
		&i.FeedURL,
		&i.FeedKind,
		&i.Platform,
		&i.NextPageIndex,
		&i.PageSize,
		&i.OverlapSize,
		&i.Status,
		&i.Attempts,
		&i.RetryAt,
		&i.EntriesSeen,
		&i.EntriesAdded,
		&i.EntriesUpdated,
		&i.LastError,
		&i.Refresh,
		&i.LockedAt,
		&i.LockedBy,
		&i.FinishedAt,
	)
	return &i, err
}

const createCatalogCrawl = `-- name: CreateCatalogCrawl :one
INSERT INTO catalog_crawls (channel_id, requested_by, feed_url, feed_kind, platform, refresh)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (channel_id, feed_kind) WHERE status IN ('queued', 'running', 'paused', 'retry_wait')
DO UPDATE SET refresh = catalog_crawls.refresh OR EXCLUDED.refresh, updated_at = NOW()
RETURNING id, created_at, updated_at, channel_id, requested_by, feed_url, feed_kind, platform, next_page_index, page_size, overlap_size, status, attempts, retry_at, entries_seen, entries_added, entries_updated, last_error, refresh, locked_at, locked_by, finished_at
`

type CreateCatalogCrawlParams struct {
	ChannelID   pgtype.UUID `db:"channel_id" json:"ChannelID"`
	RequestedBy pgtype.UUID `db:"requested_by" json:"RequestedBy"`
	FeedURL     string      `db:"feed_url" json:"FeedUrl"`
	FeedKind    string      `db:"feed_kind" json:"FeedKind"`
	Platform    string      `db:"platform" json:"Platform"`
	Refresh     bool        `db:"refresh" json:"Refresh"`
}

// CreateCatalogCrawl
//
//	INSERT INTO catalog_crawls (channel_id, requested_by, feed_url, feed_kind, platform, refresh)
//	VALUES ($1, $2, $3, $4, $5, $6)
//	ON CONFLICT (channel_id, feed_kind) WHERE status IN ('queued', 'running', 'paused', 'retry_wait')
//	DO UPDATE SET refresh = catalog_crawls.refresh OR EXCLUDED.refresh, updated_at = NOW()
//	RETURNING id, created_at, updated_at, channel_id, requested_by, feed_url, feed_kind, platform, next_page_index, page_size, overlap_size, status, attempts, retry_at, entries_seen, entries_added, entries_updated, last_error, refresh, locked_at, locked_by, finished_at
func (q *Queries) CreateCatalogCrawl(ctx context.Context, arg *CreateCatalogCrawlParams) (*CatalogCrawl, error) {
	row := q.db.QueryRow(ctx, createCatalogCrawl,
		arg.ChannelID,
		arg.RequestedBy,
		arg.FeedURL,
		arg.FeedKind,
		arg.Platform,
		arg.Refresh,
	)
	var i CatalogCrawl
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ChannelID,
		&i.RequestedBy,
		&i.FeedURL,
		&i.FeedKind,
		&i.Platform,
		&i.NextPageIndex,
		&i.PageSize,
		&i.OverlapSize,
		&i.Status,
		&i.Attempts,
		&i.RetryAt,
		&i.EntriesSeen,
		&i.EntriesAdded,
		&i.EntriesUpdated,
		&i.LastError,
		&i.Refresh,
		&i.LockedAt,
		&i.LockedBy,
		&i.FinishedAt,
	)
	return &i, err
}

const enqueueCatalogMetadataJobs = `-- name: EnqueueCatalogMetadataJobs :execrows
INSERT INTO download_jobs (url, archived_by, status, kind)
SELECT u, $1, 'queued', 'metadata'
FROM unnest($2::text[]) AS u
`

type EnqueueCatalogMetadataJobsParams struct {
	ArchivedBy pgtype.UUID `db:"archived_by" json:"ArchivedBy"`
	Urls       []string    `db:"urls" json:"Urls"`
}

// EnqueueCatalogMetadataJobs
//
//	INSERT INTO download_jobs (url, archived_by, status, kind)
//	SELECT u, $1, 'queued', 'metadata'
//	FROM unnest($2::text[]) AS u
func (q *Queries) EnqueueCatalogMetadataJobs(ctx context.Context, arg *EnqueueCatalogMetadataJobsParams) (int64, error) {
	result, err := q.db.Exec(ctx, enqueueCatalogMetadataJobs, arg.ArchivedBy, arg.Urls)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const enqueueSubtitleBackfillJobs = `-- name: EnqueueSubtitleBackfillJobs :execrows
INSERT INTO download_jobs (url, archived_by, status, kind)
SELECT v.src, v.archived_by, 'queued', 'metadata'
FROM videos v
WHERE NOT EXISTS (SELECT 1 FROM video_transcripts vt WHERE vt.video_id = v.id)
  AND v.subtitle_state <> 'unavailable'
  AND NOT EXISTS (
      SELECT 1 FROM download_jobs dj
      WHERE (dj.video_id = v.id OR dj.url = v.src)
        AND dj.status IN ('queued', 'processing')
  )
ORDER BY v.subtitle_checked_at NULLS FIRST, v.created_at
LIMIT $1
`

// EnqueueSubtitleBackfillJobs
//
//	INSERT INTO download_jobs (url, archived_by, status, kind)
//	SELECT v.src, v.archived_by, 'queued', 'metadata'
//	FROM videos v
//	WHERE NOT EXISTS (SELECT 1 FROM video_transcripts vt WHERE vt.video_id = v.id)
//	  AND v.subtitle_state <> 'unavailable'
//	  AND NOT EXISTS (
//	      SELECT 1 FROM download_jobs dj
//	      WHERE (dj.video_id = v.id OR dj.url = v.src)
//	        AND dj.status IN ('queued', 'processing')
//	  )
//	ORDER BY v.subtitle_checked_at NULLS FIRST, v.created_at
//	LIMIT $1
func (q *Queries) EnqueueSubtitleBackfillJobs(ctx context.Context, pageLimit int32) (int64, error) {
	result, err := q.db.Exec(ctx, enqueueSubtitleBackfillJobs, pageLimit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCatalogCrawl = `-- name: GetCatalogCrawl :one
SELECT id, created_at, updated_at, channel_id, requested_by, feed_url, feed_kind, platform, next_page_index, page_size, overlap_size, status, attempts, retry_at, entries_seen, entries_added, entries_updated, last_error, refresh, locked_at, locked_by, finished_at FROM catalog_crawls WHERE id = $1
`

// GetCatalogCrawl
//
//	SELECT id, created_at, updated_at, channel_id, requested_by, feed_url, feed_kind, platform, next_page_index, page_size, overlap_size, status, attempts, retry_at, entries_seen, entries_added, entries_updated, last_error, refresh, locked_at, locked_by, finished_at FROM catalog_crawls WHERE id = $1
func (q *Queries) GetCatalogCrawl(ctx context.Context, id pgtype.UUID) (*CatalogCrawl, error) {
	row := q.db.QueryRow(ctx, getCatalogCrawl, id)
	var i CatalogCrawl
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ChannelID,
		&i.RequestedBy,
		&i.FeedURL,
		&i.FeedKind,
		&i.Platform,
		&i.NextPageIndex,
		&i.PageSize,
		&i.OverlapSize,
		&i.Status,
		&i.Attempts,
		&i.RetryAt,
		&i.EntriesSeen,
		&i.EntriesAdded,
		&i.EntriesUpdated,
		&i.LastError,
		&i.Refresh,
		&i.LockedAt,
		&i.LockedBy,
		&i.FinishedAt,
	)
	return &i, err
}

const listCatalogCandidateStates = `-- name: ListCatalogCandidateStates :many
SELECT v.id, v.subtitle_state,
       EXISTS (SELECT 1 FROM video_transcripts vt WHERE vt.video_id = v.id) AS has_transcript
FROM videos v WHERE v.id = ANY($1::uuid[])
`

type ListCatalogCandidateStatesRow struct {
	ID            pgtype.UUID `db:"id" json:"ID"`
	SubtitleState string      `db:"subtitle_state" json:"SubtitleState"`
	HasTranscript bool        `db:"has_transcript" json:"HasTranscript"`
}

// ListCatalogCandidateStates
//
//	SELECT v.id, v.subtitle_state,
//	       EXISTS (SELECT 1 FROM video_transcripts vt WHERE vt.video_id = v.id) AS has_transcript
//	FROM videos v WHERE v.id = ANY($1::uuid[])
func (q *Queries) ListCatalogCandidateStates(ctx context.Context, ids []pgtype.UUID) ([]*ListCatalogCandidateStatesRow, error) {
	rows, err := q.db.Query(ctx, listCatalogCandidateStates, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListCatalogCandidateStatesRow
	for rows.Next() {
		var i ListCatalogCandidateStatesRow
		if err := rows.Scan(&i.ID, &i.SubtitleState, &i.HasTranscript); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCatalogCrawlsForChannel = `-- name: ListCatalogCrawlsForChannel :many
SELECT id, created_at, updated_at, channel_id, requested_by, feed_url, feed_kind, platform, next_page_index, page_size, overlap_size, status, attempts, retry_at, entries_seen, entries_added, entries_updated, last_error, refresh, locked_at, locked_by, finished_at FROM catalog_crawls WHERE channel_id = $1
ORDER BY created_at DESC
`

// ListCatalogCrawlsForChannel
//
//	SELECT id, created_at, updated_at, channel_id, requested_by, feed_url, feed_kind, platform, next_page_index, page_size, overlap_size, status, attempts, retry_at, entries_seen, entries_added, entries_updated, last_error, refresh, locked_at, locked_by, finished_at FROM catalog_crawls WHERE channel_id = $1
//	ORDER BY created_at DESC
func (q *Queries) ListCatalogCrawlsForChannel(ctx context.Context, channelID pgtype.UUID) ([]*CatalogCrawl, error) {
	rows, err := q.db.Query(ctx, listCatalogCrawlsForChannel, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*CatalogCrawl
	for rows.Next() {
		var i CatalogCrawl
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ChannelID,
			&i.RequestedBy,
			&i.FeedURL,
			&i.FeedKind,
			&i.Platform,
			&i.NextPageIndex,
			&i.PageSize,
			&i.OverlapSize,
			&i.Status,
			&i.Attempts,
			&i.RetryAt,
			&i.EntriesSeen,
			&i.EntriesAdded,
			&i.EntriesUpdated,
			&i.LastError,
			&i.Refresh,
			&i.LockedAt,
			&i.LockedBy,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCatalogCrawlsForCreator = `-- name: ListCatalogCrawlsForCreator :many
SELECT cc.id, cc.created_at, cc.updated_at, cc.channel_id, cc.requested_by, cc.feed_url, cc.feed_kind, cc.platform, cc.next_page_index, cc.page_size, cc.overlap_size, cc.status, cc.attempts, cc.retry_at, cc.entries_seen, cc.entries_added, cc.entries_updated, cc.last_error, cc.refresh, cc.locked_at, cc.locked_by, cc.finished_at, COALESCE(ch.uploader, ch.identity_key) AS channel_name
FROM catalog_crawls cc
JOIN channels ch ON ch.id = cc.channel_id
WHERE ch.creator_id = $1
ORDER BY cc.created_at DESC
`

type ListCatalogCrawlsForCreatorRow struct {
	ID             pgtype.UUID        `db:"id" json:"ID"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"CreatedAt"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"UpdatedAt"`
	ChannelID      pgtype.UUID        `db:"channel_id" json:"ChannelID"`
	RequestedBy    pgtype.UUID        `db:"requested_by" json:"RequestedBy"`
	FeedURL        string             `db:"feed_url" json:"FeedUrl"`
	FeedKind       string             `db:"feed_kind" json:"FeedKind"`
	Platform       string             `db:"platform" json:"Platform"`
	NextPageIndex  int32              `db:"next_page_index" json:"NextPageIndex"`
	PageSize       int32              `db:"page_size" json:"PageSize"`
	OverlapSize    int32              `db:"overlap_size" json:"OverlapSize"`
	Status         string             `db:"status" json:"Status"`
	Attempts       int32              `db:"attempts" json:"Attempts"`
	RetryAt        pgtype.Timestamptz `db:"retry_at" json:"RetryAt"`
	EntriesSeen    int64              `db:"entries_seen" json:"EntriesSeen"`
	EntriesAdded   int64              `db:"entries_added" json:"EntriesAdded"`
	EntriesUpdated int64              `db:"entries_updated" json:"EntriesUpdated"`
	LastError      string             `db:"last_error" json:"LastError"`
	Refresh        bool               `db:"refresh" json:"Refresh"`
	LockedAt       pgtype.Timestamptz `db:"locked_at" json:"LockedAt"`
	LockedBy       string             `db:"locked_by" json:"LockedBy"`
	FinishedAt     pgtype.Timestamptz `db:"finished_at" json:"FinishedAt"`
	ChannelName    string             `db:"channel_name" json:"ChannelName"`
}

// ListCatalogCrawlsForCreator
//
//	SELECT cc.id, cc.created_at, cc.updated_at, cc.channel_id, cc.requested_by, cc.feed_url, cc.feed_kind, cc.platform, cc.next_page_index, cc.page_size, cc.overlap_size, cc.status, cc.attempts, cc.retry_at, cc.entries_seen, cc.entries_added, cc.entries_updated, cc.last_error, cc.refresh, cc.locked_at, cc.locked_by, cc.finished_at, COALESCE(ch.uploader, ch.identity_key) AS channel_name
//	FROM catalog_crawls cc
//	JOIN channels ch ON ch.id = cc.channel_id
//	WHERE ch.creator_id = $1
//	ORDER BY cc.created_at DESC
func (q *Queries) ListCatalogCrawlsForCreator(ctx context.Context, creatorID pgtype.UUID) ([]*ListCatalogCrawlsForCreatorRow, error) {
	rows, err := q.db.Query(ctx, listCatalogCrawlsForCreator, creatorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListCatalogCrawlsForCreatorRow
	for rows.Next() {
		var i ListCatalogCrawlsForCreatorRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ChannelID,
			&i.RequestedBy,
			&i.FeedURL,
			&i.FeedKind,
			&i.Platform,
			&i.NextPageIndex,
			&i.PageSize,
			&i.OverlapSize,
			&i.Status,
			&i.Attempts,
			&i.RetryAt,
			&i.EntriesSeen,
			&i.EntriesAdded,
			&i.EntriesUpdated,
			&i.LastError,
			&i.Refresh,
			&i.LockedAt,
			&i.LockedBy,
			&i.FinishedAt,
			&i.ChannelName,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVideosNeedingSubtitles = `-- name: ListVideosNeedingSubtitles :many
SELECT id, src FROM videos
WHERE NOT EXISTS (SELECT 1 FROM video_transcripts vt WHERE vt.video_id = videos.id)
  AND subtitle_state <> 'unavailable'
ORDER BY subtitle_checked_at NULLS FIRST, created_at
LIMIT $1
`

type ListVideosNeedingSubtitlesRow struct {
	ID  pgtype.UUID `db:"id" json:"ID"`
	Src string      `db:"src" json:"Src"`
}

// ListVideosNeedingSubtitles
//
//	SELECT id, src FROM videos
//	WHERE NOT EXISTS (SELECT 1 FROM video_transcripts vt WHERE vt.video_id = videos.id)
//	  AND subtitle_state <> 'unavailable'
//	ORDER BY subtitle_checked_at NULLS FIRST, created_at
//	LIMIT $1
func (q *Queries) ListVideosNeedingSubtitles(ctx context.Context, pageLimit int32) ([]*ListVideosNeedingSubtitlesRow, error) {
	rows, err := q.db.Query(ctx, listVideosNeedingSubtitles, pageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListVideosNeedingSubtitlesRow
	for rows.Next() {
		var i ListVideosNeedingSubtitlesRow
		if err := rows.Scan(&i.ID, &i.Src); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recoverCatalogCrawls = `-- name: RecoverCatalogCrawls :exec
UPDATE catalog_crawls SET status = 'queued', locked_at = NULL, locked_by = '', updated_at = NOW()
WHERE status = 'running' AND (locked_at IS NULL OR locked_at < NOW() - INTERVAL '15 minutes')
`

// RecoverCatalogCrawls
//
//	UPDATE catalog_crawls SET status = 'queued', locked_at = NULL, locked_by = '', updated_at = NOW()
//	WHERE status = 'running' AND (locked_at IS NULL OR locked_at < NOW() - INTERVAL '15 minutes')
func (q *Queries) RecoverCatalogCrawls(ctx context.Context) error {
	_, err := q.db.Exec(ctx, recoverCatalogCrawls)
	return err
}

const setCatalogCrawlStatus = `-- name: SetCatalogCrawlStatus :exec
UPDATE catalog_crawls SET status = $1, last_error = $2,
    retry_at = $3, locked_at = NULL, locked_by = '',
    finished_at = CASE WHEN $1::text IN ('complete', 'cancelled', 'failed') THEN NOW() ELSE finished_at END,
    updated_at = NOW()
WHERE id = $4
`

type SetCatalogCrawlStatusParams struct {
	Status    string             `db:"status" json:"Status"`
	LastError string             `db:"last_error" json:"LastError"`
	RetryAt   pgtype.Timestamptz `db:"retry_at" json:"RetryAt"`
	ID        pgtype.UUID        `db:"id" json:"ID"`
}

// SetCatalogCrawlStatus
//
//	UPDATE catalog_crawls SET status = $1, last_error = $2,
//	    retry_at = $3, locked_at = NULL, locked_by = '',
//	    finished_at = CASE WHEN $1::text IN ('complete', 'cancelled', 'failed') THEN NOW() ELSE finished_at END,
//	    updated_at = NOW()
//	WHERE id = $4
func (q *Queries) SetCatalogCrawlStatus(ctx context.Context, arg *SetCatalogCrawlStatusParams) error {
	_, err := q.db.Exec(ctx, setCatalogCrawlStatus,
		arg.Status,
		arg.LastError,
		arg.RetryAt,
		arg.ID,
	)
	return err
}

const setRunningCatalogCrawlStatus = `-- name: SetRunningCatalogCrawlStatus :exec
UPDATE catalog_crawls SET status = $1, last_error = $2,
    retry_at = $3, locked_at = NULL, locked_by = '',
    finished_at = CASE WHEN $1::text IN ('complete', 'failed') THEN NOW() ELSE finished_at END,
    updated_at = NOW()
WHERE id = $4 AND status = 'running'
`

type SetRunningCatalogCrawlStatusParams struct {
	Status    string             `db:"status" json:"Status"`
	LastError string             `db:"last_error" json:"LastError"`
	RetryAt   pgtype.Timestamptz `db:"retry_at" json:"RetryAt"`
	ID        pgtype.UUID        `db:"id" json:"ID"`
}

// SetRunningCatalogCrawlStatus only advances a crawl that is still owned by a
// worker. A pause or cancel issued while yt-dlp is running therefore wins.
//
//	UPDATE catalog_crawls SET status = $1, last_error = $2,
//	    retry_at = $3, locked_at = NULL, locked_by = '',
//	    finished_at = CASE WHEN $1::text IN ('complete', 'failed') THEN NOW() ELSE finished_at END,
//	    updated_at = NOW()
//	WHERE id = $4 AND status = 'running'
func (q *Queries) SetRunningCatalogCrawlStatus(ctx context.Context, arg *SetRunningCatalogCrawlStatusParams) error {
	_, err := q.db.Exec(ctx, setRunningCatalogCrawlStatus,
		arg.Status,
		arg.LastError,
		arg.RetryAt,
		arg.ID,
	)
	return err
}

const setVideoSubtitleState = `-- name: SetVideoSubtitleState :exec
UPDATE videos SET subtitle_state = $1, subtitle_checked_at = NOW(),
    subtitle_last_error = $2, updated_at = NOW()
WHERE id = $3
`

type SetVideoSubtitleStateParams struct {
	SubtitleState string      `db:"subtitle_state" json:"SubtitleState"`
	LastError     string      `db:"last_error" json:"LastError"`
	ID            pgtype.UUID `db:"id" json:"ID"`
}

// SetVideoSubtitleState
//
//	UPDATE videos SET subtitle_state = $1, subtitle_checked_at = NOW(),
//	    subtitle_last_error = $2, updated_at = NOW()
//	WHERE id = $3
func (q *Queries) SetVideoSubtitleState(ctx context.Context, arg *SetVideoSubtitleStateParams) error {
	_, err := q.db.Exec(ctx, setVideoSubtitleState, arg.SubtitleState, arg.LastError, arg.ID)
	return err
}
