// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: channel_queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bumpChannelEdge = `-- name: BumpChannelEdge :execrows
UPDATE channel_edges SET weight = weight + 1, evidence = $1,
  to_channel_id = COALESCE(channel_edges.to_channel_id, $2),
  video_id = COALESCE(channel_edges.video_id, $3),
  updated_at = NOW()
WHERE from_channel_id = $4
  AND kind = $5
  AND COALESCE(channel_edges.to_channel_id::text, channel_edges.to_url) = $6::text
`

type BumpChannelEdgeParams struct {
	Evidence      string      `db:"evidence" json:"Evidence"`
	ToChannelID   pgtype.UUID `db:"to_channel_id" json:"ToChannelID"`
	VideoID       pgtype.UUID `db:"video_id" json:"VideoID"`
	FromChannelID pgtype.UUID `db:"from_channel_id" json:"FromChannelID"`
	Kind          string      `db:"kind" json:"Kind"`
	EdgeKey       string      `db:"edge_key" json:"EdgeKey"`
}

// BumpChannelEdge increments an existing directed edge (matched by the unique
// identity expression) and fills in a resolved to_channel_id / video_id when
// those were previously null.
//
//	UPDATE channel_edges SET weight = weight + 1, evidence = $1,
//	  to_channel_id = COALESCE(channel_edges.to_channel_id, $2),
//	  video_id = COALESCE(channel_edges.video_id, $3),
//	  updated_at = NOW()
//	WHERE from_channel_id = $4
//	  AND kind = $5
//	  AND COALESCE(channel_edges.to_channel_id::text, channel_edges.to_url) = $6::text
func (q *Queries) BumpChannelEdge(ctx context.Context, arg *BumpChannelEdgeParams) (int64, error) {
	result, err := q.db.Exec(ctx, bumpChannelEdge,
		arg.Evidence,
		arg.ToChannelID,
		arg.VideoID,
		arg.FromChannelID,
		arg.Kind,
		arg.EdgeKey,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const claimVideosForLinkHarvest = `-- name: ClaimVideosForLinkHarvest :many
UPDATE videos
SET links_harvested_at = NOW()
WHERE id IN (
    SELECT v.id
    FROM videos v
    WHERE v.channel_row_id IS NOT NULL
      AND v.links_harvested_at IS NULL
    ORDER BY EXISTS (
        SELECT 1 FROM channels ch
        WHERE ch.id = v.channel_row_id AND ch.creator_id IS NOT NULL
    ) DESC, v.created_at DESC
    LIMIT $1::int
    FOR UPDATE OF v SKIP LOCKED
)
RETURNING id, channel_row_id, title, description
`

type ClaimVideosForLinkHarvestRow struct {
	ID           pgtype.UUID `db:"id" json:"ID"`
	ChannelRowID pgtype.UUID `db:"channel_row_id" json:"ChannelRowID"`
	Title        string      `db:"title" json:"Title"`
	Description  string      `db:"description" json:"Description"`
}

// ClaimVideosForLinkHarvest marks a batch of attached videos for outlink harvest.
//
//	UPDATE videos
//	SET links_harvested_at = NOW()
//	WHERE id IN (
//	    SELECT v.id
//	    FROM videos v
//	    WHERE v.channel_row_id IS NOT NULL
//	      AND v.links_harvested_at IS NULL
//	    ORDER BY EXISTS (
//	        SELECT 1 FROM channels ch
//	        WHERE ch.id = v.channel_row_id AND ch.creator_id IS NOT NULL
//	    ) DESC, v.created_at DESC
//	    LIMIT $1::int
//	    FOR UPDATE OF v SKIP LOCKED
//	)
//	RETURNING id, channel_row_id, title, description
func (q *Queries) ClaimVideosForLinkHarvest(ctx context.Context, batchSize int32) ([]*ClaimVideosForLinkHarvestRow, error) {
	rows, err := q.db.Query(ctx, claimVideosForLinkHarvest, batchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ClaimVideosForLinkHarvestRow
	for rows.Next() {
		var i ClaimVideosForLinkHarvestRow
		if err := rows.Scan(
			&i.ID,
			&i.ChannelRowID,
			&i.Title,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChannel = `-- name: GetChannel :one
SELECT id, created_at, updated_at, platform, identity_key, channel_id, uploader, canonical_url, creator_id, search FROM channels WHERE id = $1
`

// GetChannel fetches one first-class channel row.
//
//	SELECT id, created_at, updated_at, platform, identity_key, channel_id, uploader, canonical_url, creator_id, search FROM channels WHERE id = $1
func (q *Queries) GetChannel(ctx context.Context, id pgtype.UUID) (*Channel, error) {
	row := q.db.QueryRow(ctx, getChannel, id)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Platform,
		&i.IdentityKey,
		&i.ChannelID,
		&i.Uploader,
		&i.CanonicalURL,
		&i.CreatorID,
		&i.Search,
	)
	return &i, err
}

const getChannelByCanonicalURL = `-- name: GetChannelByCanonicalURL :one
SELECT id, created_at, updated_at, platform, identity_key, channel_id, uploader, canonical_url, creator_id, search FROM channels
WHERE canonical_url <> '' AND (
    canonical_url = $1
    OR rtrim(replace(replace(lower(canonical_url), 'https://www.', 'https://'), 'http://www.', 'http://'), '/')
     = rtrim(replace(replace(lower($1), 'https://www.', 'https://'), 'http://www.', 'http://'), '/')
)
LIMIT 1
`

// GetChannelByCanonicalURL matches a stored canonical URL, ignoring www / trailing slash.
//
//	SELECT id, created_at, updated_at, platform, identity_key, channel_id, uploader, canonical_url, creator_id, search FROM channels
//	WHERE canonical_url <> '' AND (
//	    canonical_url = $1
//	    OR rtrim(replace(replace(lower(canonical_url), 'https://www.', 'https://'), 'http://www.', 'http://'), '/')
//	     = rtrim(replace(replace(lower($1), 'https://www.', 'https://'), 'http://www.', 'http://'), '/')
//	)
//	LIMIT 1
func (q *Queries) GetChannelByCanonicalURL(ctx context.Context, url string) (*Channel, error) {
	row := q.db.QueryRow(ctx, getChannelByCanonicalURL, url)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Platform,
		&i.IdentityKey,
		&i.ChannelID,
		&i.Uploader,
		&i.CanonicalURL,
		&i.CreatorID,
		&i.Search,
	)
	return &i, err
}

const getChannelByChannelID = `-- name: GetChannelByChannelID :one
SELECT id, created_at, updated_at, platform, identity_key, channel_id, uploader, canonical_url, creator_id, search FROM channels
WHERE platform = $1
  AND channel_id = $2
  AND channel_id <> ''
LIMIT 1
`

type GetChannelByChannelIDParams struct {
	Platform  string `db:"platform" json:"Platform"`
	ChannelID string `db:"channel_id" json:"ChannelID"`
}

// GetChannelByChannelID looks up a channel by platform + native channel_id (UC…).
//
//	SELECT id, created_at, updated_at, platform, identity_key, channel_id, uploader, canonical_url, creator_id, search FROM channels
//	WHERE platform = $1
//	  AND channel_id = $2
//	  AND channel_id <> ''
//	LIMIT 1
func (q *Queries) GetChannelByChannelID(ctx context.Context, arg *GetChannelByChannelIDParams) (*Channel, error) {
	row := q.db.QueryRow(ctx, getChannelByChannelID, arg.Platform, arg.ChannelID)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Platform,
		&i.IdentityKey,
		&i.ChannelID,
		&i.Uploader,
		&i.CanonicalURL,
		&i.CreatorID,
		&i.Search,
	)
	return &i, err
}

const getChannelByHandleGuess = `-- name: GetChannelByHandleGuess :one
SELECT id, created_at, updated_at, platform, identity_key, channel_id, uploader, canonical_url, creator_id, search FROM channels
WHERE platform = $1
  AND (
    identity_key ILIKE $2
    OR identity_key ILIKE '@' || $2
    OR uploader ILIKE $2
  )
ORDER BY
    CASE
        WHEN identity_key ILIKE '@' || $2 THEN 0
        WHEN identity_key ILIKE $2 THEN 1
        ELSE 2
    END
LIMIT 1
`

type GetChannelByHandleGuessParams struct {
	Platform string `db:"platform" json:"Platform"`
	Handle   string `db:"handle" json:"Handle"`
}

// GetChannelByHandleGuess matches a @handle to an archived channel's identity or uploader.
//
//	SELECT id, created_at, updated_at, platform, identity_key, channel_id, uploader, canonical_url, creator_id, search FROM channels
//	WHERE platform = $1
//	  AND (
//	    identity_key ILIKE $2
//	    OR identity_key ILIKE '@' || $2
//	    OR uploader ILIKE $2
//	  )
//	ORDER BY
//	    CASE
//	        WHEN identity_key ILIKE '@' || $2 THEN 0
//	        WHEN identity_key ILIKE $2 THEN 1
//	        ELSE 2
//	    END
//	LIMIT 1
func (q *Queries) GetChannelByHandleGuess(ctx context.Context, arg *GetChannelByHandleGuessParams) (*Channel, error) {
	row := q.db.QueryRow(ctx, getChannelByHandleGuess, arg.Platform, arg.Handle)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Platform,
		&i.IdentityKey,
		&i.ChannelID,
		&i.Uploader,
		&i.CanonicalURL,
		&i.CreatorID,
		&i.Search,
	)
	return &i, err
}

const getChannelByIdentity = `-- name: GetChannelByIdentity :one
SELECT id, created_at, updated_at, platform, identity_key, channel_id, uploader, canonical_url, creator_id, search FROM channels WHERE platform = $1 AND identity_key = $2
`

type GetChannelByIdentityParams struct {
	Platform    string `db:"platform" json:"Platform"`
	IdentityKey string `db:"identity_key" json:"IdentityKey"`
}

// GetChannelByIdentity looks up a channel by platform + identity_key.
//
//	SELECT id, created_at, updated_at, platform, identity_key, channel_id, uploader, canonical_url, creator_id, search FROM channels WHERE platform = $1 AND identity_key = $2
func (q *Queries) GetChannelByIdentity(ctx context.Context, arg *GetChannelByIdentityParams) (*Channel, error) {
	row := q.db.QueryRow(ctx, getChannelByIdentity, arg.Platform, arg.IdentityKey)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Platform,
		&i.IdentityKey,
		&i.ChannelID,
		&i.Uploader,
		&i.CanonicalURL,
		&i.CreatorID,
		&i.Search,
	)
	return &i, err
}

const getChannelByTwitterHandle = `-- name: GetChannelByTwitterHandle :one
SELECT id, created_at, updated_at, platform, identity_key, channel_id, uploader, canonical_url, creator_id, search FROM channels
WHERE canonical_url ~* ('^https?://(www\.)?(twitter|x)\.com/' || $1 || '/?$')
LIMIT 1
`

// GetChannelByTwitterHandle matches twitter.com / x.com profile URLs.
//
//	SELECT id, created_at, updated_at, platform, identity_key, channel_id, uploader, canonical_url, creator_id, search FROM channels
//	WHERE canonical_url ~* ('^https?://(www\.)?(twitter|x)\.com/' || $1 || '/?$')
//	LIMIT 1
func (q *Queries) GetChannelByTwitterHandle(ctx context.Context, handle *string) (*Channel, error) {
	row := q.db.QueryRow(ctx, getChannelByTwitterHandle, handle)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Platform,
		&i.IdentityKey,
		&i.ChannelID,
		&i.Uploader,
		&i.CanonicalURL,
		&i.CreatorID,
		&i.Search,
	)
	return &i, err
}

const getChannelOverview = `-- name: GetChannelOverview :one
WITH agg AS (
    SELECT
        v.uploader,
        COUNT(*) AS video_count,
        COALESCE(SUM(v.duration_seconds), 0)::bigint AS total_duration_seconds,
        COALESCE(SUM(v.file_size), 0)::bigint AS total_size_bytes,
        COALESCE(SUM(v.view_count), 0)::bigint AS total_views,
        MAX(v.upload_date)::date AS latest_upload,
        (COALESCE(MAX(NULLIF(v.channel_url, '')), MAX(NULLIF(v.uploader_url, '')), ''))::text AS channel_url,
        (COALESCE(MAX(NULLIF(v.uploader_url, '')), ''))::text AS uploader_url
    FROM videos v
    WHERE v.uploader = $1
    GROUP BY v.uploader
)
SELECT agg.uploader, agg.video_count, agg.total_duration_seconds, agg.total_size_bytes, agg.total_views, agg.latest_upload, agg.channel_url, agg.uploader_url, w.id AS watch_id
FROM agg
LEFT JOIN LATERAL (
    SELECT wc.id FROM watched_channels wc
    WHERE (agg.channel_url <> '' AND wc.url = agg.channel_url)
       OR (agg.uploader_url <> '' AND wc.url = agg.uploader_url)
       OR wc.label = agg.uploader
    LIMIT 1
) w ON TRUE
`

type GetChannelOverviewRow struct {
	Uploader             string      `db:"uploader" json:"Uploader"`
	VideoCount           int64       `db:"video_count" json:"VideoCount"`
	TotalDurationSeconds int64       `db:"total_duration_seconds" json:"TotalDurationSeconds"`
	TotalSizeBytes       int64       `db:"total_size_bytes" json:"TotalSizeBytes"`
	TotalViews           int64       `db:"total_views" json:"TotalViews"`
	LatestUpload         pgtype.Date `db:"latest_upload" json:"LatestUpload"`
	ChannelURL           string      `db:"channel_url" json:"ChannelUrl"`
	UploaderURL          string      `db:"uploader_url" json:"UploaderUrl"`
	WatchID              pgtype.UUID `db:"watch_id" json:"WatchID"`
}

// GetChannelOverview returns the aggregate stats for one uploader, plus the
// id of a matching channel watch when one exists.
//
//	WITH agg AS (
//	    SELECT
//	        v.uploader,
//	        COUNT(*) AS video_count,
//	        COALESCE(SUM(v.duration_seconds), 0)::bigint AS total_duration_seconds,
//	        COALESCE(SUM(v.file_size), 0)::bigint AS total_size_bytes,
//	        COALESCE(SUM(v.view_count), 0)::bigint AS total_views,
//	        MAX(v.upload_date)::date AS latest_upload,
//	        (COALESCE(MAX(NULLIF(v.channel_url, '')), MAX(NULLIF(v.uploader_url, '')), ''))::text AS channel_url,
//	        (COALESCE(MAX(NULLIF(v.uploader_url, '')), ''))::text AS uploader_url
//	    FROM videos v
//	    WHERE v.uploader = $1
//	    GROUP BY v.uploader
//	)
//	SELECT agg.uploader, agg.video_count, agg.total_duration_seconds, agg.total_size_bytes, agg.total_views, agg.latest_upload, agg.channel_url, agg.uploader_url, w.id AS watch_id
//	FROM agg
//	LEFT JOIN LATERAL (
//	    SELECT wc.id FROM watched_channels wc
//	    WHERE (agg.channel_url <> '' AND wc.url = agg.channel_url)
//	       OR (agg.uploader_url <> '' AND wc.url = agg.uploader_url)
//	       OR wc.label = agg.uploader
//	    LIMIT 1
//	) w ON TRUE
func (q *Queries) GetChannelOverview(ctx context.Context, uploader string) (*GetChannelOverviewRow, error) {
	row := q.db.QueryRow(ctx, getChannelOverview, uploader)
	var i GetChannelOverviewRow
	err := row.Scan(
		&i.Uploader,
		&i.VideoCount,
		&i.TotalDurationSeconds,
		&i.TotalSizeBytes,
		&i.TotalViews,
		&i.LatestUpload,
		&i.ChannelURL,
		&i.UploaderURL,
		&i.WatchID,
	)
	return &i, err
}

const insertChannelEdge = `-- name: InsertChannelEdge :exec
INSERT INTO channel_edges (from_channel_id, to_channel_id, to_url, kind, evidence, video_id)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertChannelEdgeParams struct {
	FromChannelID pgtype.UUID `db:"from_channel_id" json:"FromChannelID"`
	ToChannelID   pgtype.UUID `db:"to_channel_id" json:"ToChannelID"`
	ToURL         string      `db:"to_url" json:"ToUrl"`
	Kind          string      `db:"kind" json:"Kind"`
	Evidence      string      `db:"evidence" json:"Evidence"`
	VideoID       pgtype.UUID `db:"video_id" json:"VideoID"`
}

// InsertChannelEdge records a new directed channel relationship.
//
//	INSERT INTO channel_edges (from_channel_id, to_channel_id, to_url, kind, evidence, video_id)
//	VALUES ($1, $2, $3, $4, $5, $6)
func (q *Queries) InsertChannelEdge(ctx context.Context, arg *InsertChannelEdgeParams) error {
	_, err := q.db.Exec(ctx, insertChannelEdge,
		arg.FromChannelID,
		arg.ToChannelID,
		arg.ToURL,
		arg.Kind,
		arg.Evidence,
		arg.VideoID,
	)
	return err
}

const listChannelEdges = `-- name: ListChannelEdges :many
SELECT e.id, e.created_at, e.updated_at, e.from_channel_id, e.to_channel_id, e.to_url, e.kind, e.evidence, e.video_id, e.weight,
  fc.uploader AS from_uploader, fc.platform AS from_platform,
  fc.creator_id AS from_creator_id, COALESCE(fcr.name, '')::text AS from_creator_name,
  COALESCE(tc.uploader, '')::text AS to_uploader, COALESCE(tc.platform, '')::text AS to_platform,
  tc.creator_id AS to_creator_id, COALESCE(tcr.name, '')::text AS to_creator_name
FROM channel_edges e
JOIN channels fc ON fc.id = e.from_channel_id
LEFT JOIN creators fcr ON fcr.id = fc.creator_id
LEFT JOIN channels tc ON tc.id = e.to_channel_id
LEFT JOIN creators tcr ON tcr.id = tc.creator_id
ORDER BY e.weight DESC
LIMIT 500
`

type ListChannelEdgesRow struct {
	ID              pgtype.UUID        `db:"id" json:"ID"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"CreatedAt"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"UpdatedAt"`
	FromChannelID   pgtype.UUID        `db:"from_channel_id" json:"FromChannelID"`
	ToChannelID     pgtype.UUID        `db:"to_channel_id" json:"ToChannelID"`
	ToURL           string             `db:"to_url" json:"ToUrl"`
	Kind            string             `db:"kind" json:"Kind"`
	Evidence        string             `db:"evidence" json:"Evidence"`
	VideoID         pgtype.UUID        `db:"video_id" json:"VideoID"`
	Weight          int32              `db:"weight" json:"Weight"`
	FromUploader    string             `db:"from_uploader" json:"FromUploader"`
	FromPlatform    string             `db:"from_platform" json:"FromPlatform"`
	FromCreatorID   pgtype.UUID        `db:"from_creator_id" json:"FromCreatorID"`
	FromCreatorName string             `db:"from_creator_name" json:"FromCreatorName"`
	ToUploader      string             `db:"to_uploader" json:"ToUploader"`
	ToPlatform      string             `db:"to_platform" json:"ToPlatform"`
	ToCreatorID     pgtype.UUID        `db:"to_creator_id" json:"ToCreatorID"`
	ToCreatorName   string             `db:"to_creator_name" json:"ToCreatorName"`
}

// ListChannelEdges returns the heaviest edges for the network page.
// Unresolved to_url rows are included — they resolve once that channel is archived.
//
//	SELECT e.id, e.created_at, e.updated_at, e.from_channel_id, e.to_channel_id, e.to_url, e.kind, e.evidence, e.video_id, e.weight,
//	  fc.uploader AS from_uploader, fc.platform AS from_platform,
//	  fc.creator_id AS from_creator_id, COALESCE(fcr.name, '')::text AS from_creator_name,
//	  COALESCE(tc.uploader, '')::text AS to_uploader, COALESCE(tc.platform, '')::text AS to_platform,
//	  tc.creator_id AS to_creator_id, COALESCE(tcr.name, '')::text AS to_creator_name
//	FROM channel_edges e
//	JOIN channels fc ON fc.id = e.from_channel_id
//	LEFT JOIN creators fcr ON fcr.id = fc.creator_id
//	LEFT JOIN channels tc ON tc.id = e.to_channel_id
//	LEFT JOIN creators tcr ON tcr.id = tc.creator_id
//	ORDER BY e.weight DESC
//	LIMIT 500
func (q *Queries) ListChannelEdges(ctx context.Context) ([]*ListChannelEdgesRow, error) {
	rows, err := q.db.Query(ctx, listChannelEdges)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListChannelEdgesRow
	for rows.Next() {
		var i ListChannelEdgesRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FromChannelID,
			&i.ToChannelID,
			&i.ToURL,
			&i.Kind,
			&i.Evidence,
			&i.VideoID,
			&i.Weight,
			&i.FromUploader,
			&i.FromPlatform,
			&i.FromCreatorID,
			&i.FromCreatorName,
			&i.ToUploader,
			&i.ToPlatform,
			&i.ToCreatorID,
			&i.ToCreatorName,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelEdgesForChannel = `-- name: ListChannelEdgesForChannel :many
SELECT e.id, e.created_at, e.updated_at, e.from_channel_id, e.to_channel_id, e.to_url, e.kind, e.evidence, e.video_id, e.weight,
  fc.uploader AS from_uploader, fc.platform AS from_platform,
  COALESCE(tc.uploader, '')::text AS to_uploader, COALESCE(tc.platform, '')::text AS to_platform
FROM channel_edges e
JOIN channels fc ON fc.id = e.from_channel_id
LEFT JOIN channels tc ON tc.id = e.to_channel_id
WHERE e.from_channel_id = $1 OR e.to_channel_id = $1
ORDER BY e.weight DESC
`

type ListChannelEdgesForChannelRow struct {
	ID            pgtype.UUID        `db:"id" json:"ID"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"CreatedAt"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"UpdatedAt"`
	FromChannelID pgtype.UUID        `db:"from_channel_id" json:"FromChannelID"`
	ToChannelID   pgtype.UUID        `db:"to_channel_id" json:"ToChannelID"`
	ToURL         string             `db:"to_url" json:"ToUrl"`
	Kind          string             `db:"kind" json:"Kind"`
	Evidence      string             `db:"evidence" json:"Evidence"`
	VideoID       pgtype.UUID        `db:"video_id" json:"VideoID"`
	Weight        int32              `db:"weight" json:"Weight"`
	FromUploader  string             `db:"from_uploader" json:"FromUploader"`
	FromPlatform  string             `db:"from_platform" json:"FromPlatform"`
	ToUploader    string             `db:"to_uploader" json:"ToUploader"`
	ToPlatform    string             `db:"to_platform" json:"ToPlatform"`
}

// ListChannelEdgesForChannel returns edges that start or end at one channel.
//
//	SELECT e.id, e.created_at, e.updated_at, e.from_channel_id, e.to_channel_id, e.to_url, e.kind, e.evidence, e.video_id, e.weight,
//	  fc.uploader AS from_uploader, fc.platform AS from_platform,
//	  COALESCE(tc.uploader, '')::text AS to_uploader, COALESCE(tc.platform, '')::text AS to_platform
//	FROM channel_edges e
//	JOIN channels fc ON fc.id = e.from_channel_id
//	LEFT JOIN channels tc ON tc.id = e.to_channel_id
//	WHERE e.from_channel_id = $1 OR e.to_channel_id = $1
//	ORDER BY e.weight DESC
func (q *Queries) ListChannelEdgesForChannel(ctx context.Context, channelID pgtype.UUID) ([]*ListChannelEdgesForChannelRow, error) {
	rows, err := q.db.Query(ctx, listChannelEdgesForChannel, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListChannelEdgesForChannelRow
	for rows.Next() {
		var i ListChannelEdgesForChannelRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FromChannelID,
			&i.ToChannelID,
			&i.ToURL,
			&i.Kind,
			&i.Evidence,
			&i.VideoID,
			&i.Weight,
			&i.FromUploader,
			&i.FromPlatform,
			&i.ToUploader,
			&i.ToPlatform,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelEdgesForCreator = `-- name: ListChannelEdgesForCreator :many
SELECT e.id, e.created_at, e.updated_at, e.from_channel_id, e.to_channel_id, e.to_url, e.kind, e.evidence, e.video_id, e.weight,
  fc.uploader AS from_uploader, fc.platform AS from_platform,
  COALESCE(tc.uploader, '')::text AS to_uploader, COALESCE(tc.platform, '')::text AS to_platform
FROM channel_edges e
JOIN channels fc ON fc.id = e.from_channel_id
LEFT JOIN channels tc ON tc.id = e.to_channel_id
WHERE fc.creator_id = $1
   OR tc.creator_id = $1
ORDER BY e.weight DESC
LIMIT 200
`

type ListChannelEdgesForCreatorRow struct {
	ID            pgtype.UUID        `db:"id" json:"ID"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"CreatedAt"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"UpdatedAt"`
	FromChannelID pgtype.UUID        `db:"from_channel_id" json:"FromChannelID"`
	ToChannelID   pgtype.UUID        `db:"to_channel_id" json:"ToChannelID"`
	ToURL         string             `db:"to_url" json:"ToUrl"`
	Kind          string             `db:"kind" json:"Kind"`
	Evidence      string             `db:"evidence" json:"Evidence"`
	VideoID       pgtype.UUID        `db:"video_id" json:"VideoID"`
	Weight        int32              `db:"weight" json:"Weight"`
	FromUploader  string             `db:"from_uploader" json:"FromUploader"`
	FromPlatform  string             `db:"from_platform" json:"FromPlatform"`
	ToUploader    string             `db:"to_uploader" json:"ToUploader"`
	ToPlatform    string             `db:"to_platform" json:"ToPlatform"`
}

// ListChannelEdgesForCreator returns edges that start or end on a creator's channels.
//
//	SELECT e.id, e.created_at, e.updated_at, e.from_channel_id, e.to_channel_id, e.to_url, e.kind, e.evidence, e.video_id, e.weight,
//	  fc.uploader AS from_uploader, fc.platform AS from_platform,
//	  COALESCE(tc.uploader, '')::text AS to_uploader, COALESCE(tc.platform, '')::text AS to_platform
//	FROM channel_edges e
//	JOIN channels fc ON fc.id = e.from_channel_id
//	LEFT JOIN channels tc ON tc.id = e.to_channel_id
//	WHERE fc.creator_id = $1
//	   OR tc.creator_id = $1
//	ORDER BY e.weight DESC
//	LIMIT 200
func (q *Queries) ListChannelEdgesForCreator(ctx context.Context, creatorID pgtype.UUID) ([]*ListChannelEdgesForCreatorRow, error) {
	rows, err := q.db.Query(ctx, listChannelEdgesForCreator, creatorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListChannelEdgesForCreatorRow
	for rows.Next() {
		var i ListChannelEdgesForCreatorRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FromChannelID,
			&i.ToChannelID,
			&i.ToURL,
			&i.Kind,
			&i.Evidence,
			&i.VideoID,
			&i.Weight,
			&i.FromUploader,
			&i.FromPlatform,
			&i.ToUploader,
			&i.ToPlatform,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannels = `-- name: ListChannels :many
WITH agg AS (
    SELECT
        v.uploader,
        COUNT(*) AS video_count,
        COALESCE(SUM(v.duration_seconds), 0)::bigint AS total_duration_seconds,
        COALESCE(SUM(v.file_size), 0)::bigint AS total_size_bytes,
        MAX(v.upload_date)::date AS latest_upload,
        (COALESCE(MAX(NULLIF(v.channel_url, '')), MAX(NULLIF(v.uploader_url, '')), ''))::text AS channel_url,
        (COALESCE(MAX(NULLIF(v.uploader_url, '')), ''))::text AS uploader_url
    FROM videos v
    WHERE btrim(v.uploader) <> ''
      AND ($1::text IS NULL OR v.uploader ILIKE '%' || $1 || '%')
    GROUP BY v.uploader
)
SELECT
    agg.uploader, agg.video_count, agg.total_duration_seconds, agg.total_size_bytes, agg.latest_upload, agg.channel_url, agg.uploader_url,
    (SELECT v2.id FROM videos v2
     WHERE v2.uploader = agg.uploader
     ORDER BY v2.upload_date DESC NULLS LAST, v2.created_at DESC
     LIMIT 1) AS latest_video_id,
    (w.id IS NOT NULL)::boolean AS watched
FROM agg
LEFT JOIN LATERAL (
    SELECT wc.id FROM watched_channels wc
    WHERE (agg.channel_url <> '' AND wc.url = agg.channel_url)
       OR (agg.uploader_url <> '' AND wc.url = agg.uploader_url)
       OR wc.label = agg.uploader
    LIMIT 1
) w ON TRUE
ORDER BY agg.video_count DESC, agg.uploader
`

type ListChannelsRow struct {
	Uploader             string      `db:"uploader" json:"Uploader"`
	VideoCount           int64       `db:"video_count" json:"VideoCount"`
	TotalDurationSeconds int64       `db:"total_duration_seconds" json:"TotalDurationSeconds"`
	TotalSizeBytes       int64       `db:"total_size_bytes" json:"TotalSizeBytes"`
	LatestUpload         pgtype.Date `db:"latest_upload" json:"LatestUpload"`
	ChannelURL           string      `db:"channel_url" json:"ChannelUrl"`
	UploaderURL          string      `db:"uploader_url" json:"UploaderUrl"`
	LatestVideoID        pgtype.UUID `db:"latest_video_id" json:"LatestVideoID"`
	Watched              bool        `db:"watched" json:"Watched"`
}

// ListChannels aggregates the library by uploader: per-channel video counts,
// totals, a representative latest video (for the thumbnail), the channel URL
// (from the generated channel_url/uploader_url columns — never the info
// JSONB, which is far too heavy to touch per row), and whether a channel
// watch already covers it. Optional name filter for the list page search box.
//
//	WITH agg AS (
//	    SELECT
//	        v.uploader,
//	        COUNT(*) AS video_count,
//	        COALESCE(SUM(v.duration_seconds), 0)::bigint AS total_duration_seconds,
//	        COALESCE(SUM(v.file_size), 0)::bigint AS total_size_bytes,
//	        MAX(v.upload_date)::date AS latest_upload,
//	        (COALESCE(MAX(NULLIF(v.channel_url, '')), MAX(NULLIF(v.uploader_url, '')), ''))::text AS channel_url,
//	        (COALESCE(MAX(NULLIF(v.uploader_url, '')), ''))::text AS uploader_url
//	    FROM videos v
//	    WHERE btrim(v.uploader) <> ''
//	      AND ($1::text IS NULL OR v.uploader ILIKE '%' || $1 || '%')
//	    GROUP BY v.uploader
//	)
//	SELECT
//	    agg.uploader, agg.video_count, agg.total_duration_seconds, agg.total_size_bytes, agg.latest_upload, agg.channel_url, agg.uploader_url,
//	    (SELECT v2.id FROM videos v2
//	     WHERE v2.uploader = agg.uploader
//	     ORDER BY v2.upload_date DESC NULLS LAST, v2.created_at DESC
//	     LIMIT 1) AS latest_video_id,
//	    (w.id IS NOT NULL)::boolean AS watched
//	FROM agg
//	LEFT JOIN LATERAL (
//	    SELECT wc.id FROM watched_channels wc
//	    WHERE (agg.channel_url <> '' AND wc.url = agg.channel_url)
//	       OR (agg.uploader_url <> '' AND wc.url = agg.uploader_url)
//	       OR wc.label = agg.uploader
//	    LIMIT 1
//	) w ON TRUE
//	ORDER BY agg.video_count DESC, agg.uploader
func (q *Queries) ListChannels(ctx context.Context, filter *string) ([]*ListChannelsRow, error) {
	rows, err := q.db.Query(ctx, listChannels, filter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListChannelsRow
	for rows.Next() {
		var i ListChannelsRow
		if err := rows.Scan(
			&i.Uploader,
			&i.VideoCount,
			&i.TotalDurationSeconds,
			&i.TotalSizeBytes,
			&i.LatestUpload,
			&i.ChannelURL,
			&i.UploaderURL,
			&i.LatestVideoID,
			&i.Watched,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVideosForAnalyze = `-- name: ListVideosForAnalyze :many
SELECT v.id, v.src, v.title, v.format, v.upload_date, v.duration_seconds, v.view_count, v.like_count,
  (SELECT COUNT(*) FROM video_comments c WHERE c.video_id = v.id)::bigint AS comment_count
FROM videos v
WHERE v.channel_row_id = ANY($1::uuid[])
  AND v.upload_date IS NOT NULL
ORDER BY v.upload_date
`

type ListVideosForAnalyzeRow struct {
	ID              pgtype.UUID `db:"id" json:"ID"`
	Src             string      `db:"src" json:"Src"`
	Title           string      `db:"title" json:"Title"`
	Format          string      `db:"format" json:"Format"`
	UploadDate      pgtype.Date `db:"upload_date" json:"UploadDate"`
	DurationSeconds *int32      `db:"duration_seconds" json:"DurationSeconds"`
	ViewCount       *int64      `db:"view_count" json:"ViewCount"`
	LikeCount       *int64      `db:"like_count" json:"LikeCount"`
	CommentCount    int64       `db:"comment_count" json:"CommentCount"`
}

// ListVideosForAnalyze returns the public-metric rows the autopsy analyzer needs.
//
//	SELECT v.id, v.src, v.title, v.format, v.upload_date, v.duration_seconds, v.view_count, v.like_count,
//	  (SELECT COUNT(*) FROM video_comments c WHERE c.video_id = v.id)::bigint AS comment_count
//	FROM videos v
//	WHERE v.channel_row_id = ANY($1::uuid[])
//	  AND v.upload_date IS NOT NULL
//	ORDER BY v.upload_date
func (q *Queries) ListVideosForAnalyze(ctx context.Context, channelIds []pgtype.UUID) ([]*ListVideosForAnalyzeRow, error) {
	rows, err := q.db.Query(ctx, listVideosForAnalyze, channelIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListVideosForAnalyzeRow
	for rows.Next() {
		var i ListVideosForAnalyzeRow
		if err := rows.Scan(
			&i.ID,
			&i.Src,
			&i.Title,
			&i.Format,
			&i.UploadDate,
			&i.DurationSeconds,
			&i.ViewCount,
			&i.LikeCount,
			&i.CommentCount,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markVideoLinksHarvested = `-- name: MarkVideoLinksHarvested :exec
UPDATE videos SET links_harvested_at = NOW() WHERE id = $1
`

// MarkVideoLinksHarvested records that title/description/comment outlinks were harvested.
//
//	UPDATE videos SET links_harvested_at = NOW() WHERE id = $1
func (q *Queries) MarkVideoLinksHarvested(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markVideoLinksHarvested, id)
	return err
}

const relabelTwitterMentionsMisfiledAsYouTube = `-- name: RelabelTwitterMentionsMisfiledAsYouTube :exec
UPDATE channel_edges e
SET
    to_url = 'https://x.com/' || substring(e.to_url from '(?i)youtube\.com/@([^/?#]+)'),
    to_channel_id = NULL,
    updated_at = NOW()
FROM channels c
WHERE e.from_channel_id = c.id
  AND e.kind = 'mention'
  AND e.to_url ~* 'youtube\.com/@'
  AND substring(e.to_url from '(?i)youtube\.com/@([^/?#]+)') IS NOT NULL
  AND (
    c.platform IN ('twitter', 'x')
    OR c.canonical_url ~* 'https?://(www\.)?(twitter|x)\.com/'
  )
  AND NOT EXISTS (
    SELECT 1 FROM channel_edges e2
    WHERE e2.from_channel_id = e.from_channel_id
      AND e2.kind = e.kind
      AND e2.id <> e.id
      AND COALESCE(e2.to_channel_id::text, e2.to_url)
        = 'https://x.com/' || substring(e.to_url from '(?i)youtube\.com/@([^/?#]+)')
  )
`

// RelabelTwitterMentionsMisfiledAsYouTube rewrites @mentions harvested as
// youtube.com/@handle when the source channel is actually Twitter/X.
//
//	UPDATE channel_edges e
//	SET
//	    to_url = 'https://x.com/' || substring(e.to_url from '(?i)youtube\.com/@([^/?#]+)'),
//	    to_channel_id = NULL,
//	    updated_at = NOW()
//	FROM channels c
//	WHERE e.from_channel_id = c.id
//	  AND e.kind = 'mention'
//	  AND e.to_url ~* 'youtube\.com/@'
//	  AND substring(e.to_url from '(?i)youtube\.com/@([^/?#]+)') IS NOT NULL
//	  AND (
//	    c.platform IN ('twitter', 'x')
//	    OR c.canonical_url ~* 'https?://(www\.)?(twitter|x)\.com/'
//	  )
//	  AND NOT EXISTS (
//	    SELECT 1 FROM channel_edges e2
//	    WHERE e2.from_channel_id = e.from_channel_id
//	      AND e2.kind = e.kind
//	      AND e2.id <> e.id
//	      AND COALESCE(e2.to_channel_id::text, e2.to_url)
//	        = 'https://x.com/' || substring(e.to_url from '(?i)youtube\.com/@([^/?#]+)')
//	  )
func (q *Queries) RelabelTwitterMentionsMisfiledAsYouTube(ctx context.Context) error {
	_, err := q.db.Exec(ctx, relabelTwitterMentionsMisfiledAsYouTube)
	return err
}

const resolveChannelEdges = `-- name: ResolveChannelEdges :exec
UPDATE channel_edges e SET to_channel_id = c.id, updated_at = NOW()
FROM channels c
WHERE e.to_channel_id IS NULL AND e.to_url <> ''
AND NOT EXISTS (
    SELECT 1 FROM channel_edges e2
    WHERE e2.from_channel_id = e.from_channel_id
      AND e2.kind = e.kind
      AND e2.id <> e.id
      AND COALESCE(e2.to_channel_id::text, e2.to_url) = c.id::text
)
AND (
    c.canonical_url = e.to_url
    OR c.identity_key = e.to_url
    OR rtrim(replace(replace(lower(c.canonical_url), 'https://www.', 'https://'), 'http://www.', 'http://'), '/')
     = rtrim(replace(replace(lower(e.to_url), 'https://www.', 'https://'), 'http://www.', 'http://'), '/')
    OR (c.channel_id <> '' AND e.to_url ILIKE '%/channel/' || c.channel_id || '%')
    OR (c.identity_key LIKE 'UC%' AND e.to_url ILIKE '%/channel/' || c.identity_key || '%')
    OR (c.identity_key LIKE '@%' AND (
         e.to_url ILIKE '%/' || c.identity_key
         OR e.to_url ILIKE '%/' || c.identity_key || '/%'
    ))
    OR (
      c.platform = 'youtube'
      AND substring(e.to_url from '(?i)youtube\.com/@([^/?#]+)') IS NOT NULL
      AND (
        c.identity_key ILIKE '@' || substring(e.to_url from '(?i)youtube\.com/@([^/?#]+)')
        OR c.uploader ILIKE substring(e.to_url from '(?i)youtube\.com/@([^/?#]+)')
      )
    )
    OR (
      substring(e.to_url from '(?i)(?:twitter|x)\.com/@?([^/?#]+)') IS NOT NULL
      AND c.canonical_url ~* ('https?://(www\.)?(twitter|x)\.com/'
        || substring(e.to_url from '(?i)(?:twitter|x)\.com/@?([^/?#]+)')
        || '/?$')
    )
)
`

// ResolveChannelEdges fills to_channel_id when an unresolved to_url now matches
// an archived channel (canonical URL, UC id, @handle, or identity key).
// Skip rows that would collide with an existing (from, kind, to_channel) identity.
//
//	UPDATE channel_edges e SET to_channel_id = c.id, updated_at = NOW()
//	FROM channels c
//	WHERE e.to_channel_id IS NULL AND e.to_url <> ''
//	AND NOT EXISTS (
//	    SELECT 1 FROM channel_edges e2
//	    WHERE e2.from_channel_id = e.from_channel_id
//	      AND e2.kind = e.kind
//	      AND e2.id <> e.id
//	      AND COALESCE(e2.to_channel_id::text, e2.to_url) = c.id::text
//	)
//	AND (
//	    c.canonical_url = e.to_url
//	    OR c.identity_key = e.to_url
//	    OR rtrim(replace(replace(lower(c.canonical_url), 'https://www.', 'https://'), 'http://www.', 'http://'), '/')
//	     = rtrim(replace(replace(lower(e.to_url), 'https://www.', 'https://'), 'http://www.', 'http://'), '/')
//	    OR (c.channel_id <> '' AND e.to_url ILIKE '%/channel/' || c.channel_id || '%')
//	    OR (c.identity_key LIKE 'UC%' AND e.to_url ILIKE '%/channel/' || c.identity_key || '%')
//	    OR (c.identity_key LIKE '@%' AND (
//	         e.to_url ILIKE '%/' || c.identity_key
//	         OR e.to_url ILIKE '%/' || c.identity_key || '/%'
//	    ))
//	    OR (
//	      c.platform = 'youtube'
//	      AND substring(e.to_url from '(?i)youtube\.com/@([^/?#]+)') IS NOT NULL
//	      AND (
//	        c.identity_key ILIKE '@' || substring(e.to_url from '(?i)youtube\.com/@([^/?#]+)')
//	        OR c.uploader ILIKE substring(e.to_url from '(?i)youtube\.com/@([^/?#]+)')
//	      )
//	    )
//	    OR (
//	      substring(e.to_url from '(?i)(?:twitter|x)\.com/@?([^/?#]+)') IS NOT NULL
//	      AND c.canonical_url ~* ('https?://(www\.)?(twitter|x)\.com/'
//	        || substring(e.to_url from '(?i)(?:twitter|x)\.com/@?([^/?#]+)')
//	        || '/?$')
//	    )
//	)
func (q *Queries) ResolveChannelEdges(ctx context.Context) error {
	_, err := q.db.Exec(ctx, resolveChannelEdges)
	return err
}

const setVideoChannelAndFormat = `-- name: SetVideoChannelAndFormat :exec
UPDATE videos
SET channel_row_id = $1,
    format = $2,
    updated_at = NOW()
WHERE id = $3
`

type SetVideoChannelAndFormatParams struct {
	ChannelRowID pgtype.UUID `db:"channel_row_id" json:"ChannelRowID"`
	Format       string      `db:"format" json:"Format"`
	ID           pgtype.UUID `db:"id" json:"ID"`
}

// SetVideoChannelAndFormat attaches a video to its channel row and stores format.
//
//	UPDATE videos
//	SET channel_row_id = $1,
//	    format = $2,
//	    updated_at = NOW()
//	WHERE id = $3
func (q *Queries) SetVideoChannelAndFormat(ctx context.Context, arg *SetVideoChannelAndFormatParams) error {
	_, err := q.db.Exec(ctx, setVideoChannelAndFormat, arg.ChannelRowID, arg.Format, arg.ID)
	return err
}

const upsertChannel = `-- name: UpsertChannel :one
INSERT INTO channels (
    platform,
    identity_key,
    channel_id,
    uploader,
    canonical_url,
    search
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    setweight(to_tsvector('simple', coalesce($4, '')), 'A')
)
ON CONFLICT (platform, identity_key)
DO UPDATE SET
    channel_id = CASE WHEN EXCLUDED.channel_id <> '' THEN EXCLUDED.channel_id ELSE channels.channel_id END,
    uploader = CASE WHEN EXCLUDED.uploader <> '' THEN EXCLUDED.uploader ELSE channels.uploader END,
    canonical_url = CASE WHEN EXCLUDED.canonical_url <> '' THEN EXCLUDED.canonical_url ELSE channels.canonical_url END,
    search = EXCLUDED.search,
    updated_at = NOW()
RETURNING id, created_at, updated_at, platform, identity_key, channel_id, uploader, canonical_url, creator_id, search
`

type UpsertChannelParams struct {
	Platform     string `db:"platform" json:"Platform"`
	IdentityKey  string `db:"identity_key" json:"IdentityKey"`
	ChannelID    string `db:"channel_id" json:"ChannelID"`
	Uploader     string `db:"uploader" json:"Uploader"`
	CanonicalURL string `db:"canonical_url" json:"CanonicalUrl"`
}

// UpsertChannel inserts or updates a first-class channel row keyed by
// platform + identity_key (channel_id / uploader_id / canonical URL).
//
//	INSERT INTO channels (
//	    platform,
//	    identity_key,
//	    channel_id,
//	    uploader,
//	    canonical_url,
//	    search
//	) VALUES (
//	    $1,
//	    $2,
//	    $3,
//	    $4,
//	    $5,
//	    setweight(to_tsvector('simple', coalesce($4, '')), 'A')
//	)
//	ON CONFLICT (platform, identity_key)
//	DO UPDATE SET
//	    channel_id = CASE WHEN EXCLUDED.channel_id <> '' THEN EXCLUDED.channel_id ELSE channels.channel_id END,
//	    uploader = CASE WHEN EXCLUDED.uploader <> '' THEN EXCLUDED.uploader ELSE channels.uploader END,
//	    canonical_url = CASE WHEN EXCLUDED.canonical_url <> '' THEN EXCLUDED.canonical_url ELSE channels.canonical_url END,
//	    search = EXCLUDED.search,
//	    updated_at = NOW()
//	RETURNING id, created_at, updated_at, platform, identity_key, channel_id, uploader, canonical_url, creator_id, search
func (q *Queries) UpsertChannel(ctx context.Context, arg *UpsertChannelParams) (*Channel, error) {
	row := q.db.QueryRow(ctx, upsertChannel,
		arg.Platform,
		arg.IdentityKey,
		arg.ChannelID,
		arg.Uploader,
		arg.CanonicalURL,
	)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Platform,
		&i.IdentityKey,
		&i.ChannelID,
		&i.Uploader,
		&i.CanonicalURL,
		&i.CreatorID,
		&i.Search,
	)
	return &i, err
}
