// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: compose_queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"thirdcoast.systems/rewind/pkg/videoinfo"
)

const createComposeJob = `-- name: CreateComposeJob :one

INSERT INTO compose_jobs (project_id, video_id, created_by, canvas, timeline, format, quality)
VALUES ($1, $2, $3,
        $4, $5, $6, $7)
RETURNING id
`

type CreateComposeJobParams struct {
	ProjectID pgtype.UUID `db:"project_id" json:"ProjectID"`
	VideoID   pgtype.UUID `db:"video_id" json:"VideoID"`
	CreatedBy pgtype.UUID `db:"created_by" json:"CreatedBy"`
	Canvas    []byte      `db:"canvas" json:"Canvas"`
	Timeline  []byte      `db:"timeline" json:"Timeline"`
	Format    string      `db:"format" json:"Format"`
	Quality   string      `db:"quality" json:"Quality"`
}

// ============================================================================
// Compose jobs (export queue)
// ============================================================================
//
//	INSERT INTO compose_jobs (project_id, video_id, created_by, canvas, timeline, format, quality)
//	VALUES ($1, $2, $3,
//	        $4, $5, $6, $7)
//	RETURNING id
func (q *Queries) CreateComposeJob(ctx context.Context, arg *CreateComposeJobParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createComposeJob,
		arg.ProjectID,
		arg.VideoID,
		arg.CreatedBy,
		arg.Canvas,
		arg.Timeline,
		arg.Format,
		arg.Quality,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createComposeProject = `-- name: CreateComposeProject :one
INSERT INTO compose_projects (video_id, created_by, title, canvas)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateComposeProjectParams struct {
	VideoID   pgtype.UUID `db:"video_id" json:"VideoID"`
	CreatedBy pgtype.UUID `db:"created_by" json:"CreatedBy"`
	Title     string      `db:"title" json:"Title"`
	Canvas    []byte      `db:"canvas" json:"Canvas"`
}

// CreateComposeProject
//
//	INSERT INTO compose_projects (video_id, created_by, title, canvas)
//	VALUES ($1, $2, $3, $4)
//	RETURNING id
func (q *Queries) CreateComposeProject(ctx context.Context, arg *CreateComposeProjectParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createComposeProject,
		arg.VideoID,
		arg.CreatedBy,
		arg.Title,
		arg.Canvas,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteComposeProject = `-- name: DeleteComposeProject :exec
DELETE FROM compose_projects
WHERE id = $1
  AND created_by = $2
`

type DeleteComposeProjectParams struct {
	ID     pgtype.UUID `db:"id" json:"ID"`
	UserID pgtype.UUID `db:"user_id" json:"UserID"`
}

// DeleteComposeProject
//
//	DELETE FROM compose_projects
//	WHERE id = $1
//	  AND created_by = $2
func (q *Queries) DeleteComposeProject(ctx context.Context, arg *DeleteComposeProjectParams) error {
	_, err := q.db.Exec(ctx, deleteComposeProject, arg.ID, arg.UserID)
	return err
}

const findAndLockPendingComposeJob = `-- name: FindAndLockPendingComposeJob :one
UPDATE compose_jobs
SET status     = 'processing',
    locked_at  = NOW(),
    locked_by  = $1,
    started_at = NOW(),
    attempts   = attempts + 1
WHERE id = (
    SELECT id FROM compose_jobs
    WHERE status = 'queued'
      AND (locked_at IS NULL OR locked_at < NOW() - INTERVAL '10 minutes')
    ORDER BY created_at ASC
    LIMIT 1
    FOR UPDATE SKIP LOCKED
)
RETURNING id, project_id, video_id, created_by, canvas, timeline, format, quality
`

type FindAndLockPendingComposeJobRow struct {
	ID        pgtype.UUID `db:"id" json:"ID"`
	ProjectID pgtype.UUID `db:"project_id" json:"ProjectID"`
	VideoID   pgtype.UUID `db:"video_id" json:"VideoID"`
	CreatedBy pgtype.UUID `db:"created_by" json:"CreatedBy"`
	Canvas    []byte      `db:"canvas" json:"Canvas"`
	Timeline  []byte      `db:"timeline" json:"Timeline"`
	Format    string      `db:"format" json:"Format"`
	Quality   string      `db:"quality" json:"Quality"`
}

// Atomically claim the oldest queued compose job for processing.
//
//	UPDATE compose_jobs
//	SET status     = 'processing',
//	    locked_at  = NOW(),
//	    locked_by  = $1,
//	    started_at = NOW(),
//	    attempts   = attempts + 1
//	WHERE id = (
//	    SELECT id FROM compose_jobs
//	    WHERE status = 'queued'
//	      AND (locked_at IS NULL OR locked_at < NOW() - INTERVAL '10 minutes')
//	    ORDER BY created_at ASC
//	    LIMIT 1
//	    FOR UPDATE SKIP LOCKED
//	)
//	RETURNING id, project_id, video_id, created_by, canvas, timeline, format, quality
func (q *Queries) FindAndLockPendingComposeJob(ctx context.Context, lockedBy *string) (*FindAndLockPendingComposeJobRow, error) {
	row := q.db.QueryRow(ctx, findAndLockPendingComposeJob, lockedBy)
	var i FindAndLockPendingComposeJobRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.VideoID,
		&i.CreatedBy,
		&i.Canvas,
		&i.Timeline,
		&i.Format,
		&i.Quality,
	)
	return &i, err
}

const finishComposeJobError = `-- name: FinishComposeJobError :exec
UPDATE compose_jobs
SET status      = 'error',
    last_error  = $1,
    finished_at = NOW(),
    locked_at   = NULL,
    locked_by   = NULL,
    pid         = NULL
WHERE id = $2
`

type FinishComposeJobErrorParams struct {
	LastError *string     `db:"last_error" json:"LastError"`
	ID        pgtype.UUID `db:"id" json:"ID"`
}

// FinishComposeJobError
//
//	UPDATE compose_jobs
//	SET status      = 'error',
//	    last_error  = $1,
//	    finished_at = NOW(),
//	    locked_at   = NULL,
//	    locked_by   = NULL,
//	    pid         = NULL
//	WHERE id = $2
func (q *Queries) FinishComposeJobError(ctx context.Context, arg *FinishComposeJobErrorParams) error {
	_, err := q.db.Exec(ctx, finishComposeJobError, arg.LastError, arg.ID)
	return err
}

const finishComposeJobReady = `-- name: FinishComposeJobReady :exec
UPDATE compose_jobs
SET status           = 'ready',
    file_path        = $1,
    size_bytes       = $2,
    duration_seconds = $3,
    progress_pct     = 100,
    finished_at      = NOW(),
    locked_at        = NULL,
    locked_by        = NULL,
    pid              = NULL,
    last_accessed_at = NOW()
WHERE id = $4
`

type FinishComposeJobReadyParams struct {
	FilePath        string      `db:"file_path" json:"FilePath"`
	SizeBytes       int64       `db:"size_bytes" json:"SizeBytes"`
	DurationSeconds *float64    `db:"duration_seconds" json:"DurationSeconds"`
	ID              pgtype.UUID `db:"id" json:"ID"`
}

// FinishComposeJobReady
//
//	UPDATE compose_jobs
//	SET status           = 'ready',
//	    file_path        = $1,
//	    size_bytes       = $2,
//	    duration_seconds = $3,
//	    progress_pct     = 100,
//	    finished_at      = NOW(),
//	    locked_at        = NULL,
//	    locked_by        = NULL,
//	    pid              = NULL,
//	    last_accessed_at = NOW()
//	WHERE id = $4
func (q *Queries) FinishComposeJobReady(ctx context.Context, arg *FinishComposeJobReadyParams) error {
	_, err := q.db.Exec(ctx, finishComposeJobReady,
		arg.FilePath,
		arg.SizeBytes,
		arg.DurationSeconds,
		arg.ID,
	)
	return err
}

const getComposeJob = `-- name: GetComposeJob :one
SELECT id, project_id, video_id, status, progress_pct, file_path, size_bytes,
       last_error, created_at, finished_at
FROM compose_jobs
WHERE id = $1
`

type GetComposeJobRow struct {
	ID          pgtype.UUID        `db:"id" json:"ID"`
	ProjectID   pgtype.UUID        `db:"project_id" json:"ProjectID"`
	VideoID     pgtype.UUID        `db:"video_id" json:"VideoID"`
	Status      ExportStatus       `db:"status" json:"Status"`
	ProgressPct int32              `db:"progress_pct" json:"ProgressPct"`
	FilePath    string             `db:"file_path" json:"FilePath"`
	SizeBytes   int64              `db:"size_bytes" json:"SizeBytes"`
	LastError   *string            `db:"last_error" json:"LastError"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"CreatedAt"`
	FinishedAt  pgtype.Timestamptz `db:"finished_at" json:"FinishedAt"`
}

// GetComposeJob
//
//	SELECT id, project_id, video_id, status, progress_pct, file_path, size_bytes,
//	       last_error, created_at, finished_at
//	FROM compose_jobs
//	WHERE id = $1
func (q *Queries) GetComposeJob(ctx context.Context, id pgtype.UUID) (*GetComposeJobRow, error) {
	row := q.db.QueryRow(ctx, getComposeJob, id)
	var i GetComposeJobRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.VideoID,
		&i.Status,
		&i.ProgressPct,
		&i.FilePath,
		&i.SizeBytes,
		&i.LastError,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return &i, err
}

const getComposeJobStatus = `-- name: GetComposeJobStatus :one
SELECT id, status, progress_pct, file_path, last_error
FROM compose_jobs
WHERE id = $1
`

type GetComposeJobStatusRow struct {
	ID          pgtype.UUID  `db:"id" json:"ID"`
	Status      ExportStatus `db:"status" json:"Status"`
	ProgressPct int32        `db:"progress_pct" json:"ProgressPct"`
	FilePath    string       `db:"file_path" json:"FilePath"`
	LastError   *string      `db:"last_error" json:"LastError"`
}

// GetComposeJobStatus
//
//	SELECT id, status, progress_pct, file_path, last_error
//	FROM compose_jobs
//	WHERE id = $1
func (q *Queries) GetComposeJobStatus(ctx context.Context, id pgtype.UUID) (*GetComposeJobStatusRow, error) {
	row := q.db.QueryRow(ctx, getComposeJobStatus, id)
	var i GetComposeJobStatusRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.ProgressPct,
		&i.FilePath,
		&i.LastError,
	)
	return &i, err
}

const getComposeProject = `-- name: GetComposeProject :one
SELECT cp.id, cp.video_id, cp.created_by, cp.title, cp.canvas, cp.timeline,
       cp.format, cp.quality, cp.created_at, cp.updated_at,
       v.title AS video_title, v.video_path,
       v.thumbnail_path, v.duration_seconds AS video_duration_seconds,
       v.probe_data
FROM compose_projects cp
LEFT JOIN videos v ON v.id = cp.video_id
WHERE cp.id = $1
`

type GetComposeProjectRow struct {
	ID                   pgtype.UUID          `db:"id" json:"ID"`
	VideoID              pgtype.UUID          `db:"video_id" json:"VideoID"`
	CreatedBy            pgtype.UUID          `db:"created_by" json:"CreatedBy"`
	Title                string               `db:"title" json:"Title"`
	Canvas               []byte               `db:"canvas" json:"Canvas"`
	Timeline             []byte               `db:"timeline" json:"Timeline"`
	Format               string               `db:"format" json:"Format"`
	Quality              string               `db:"quality" json:"Quality"`
	CreatedAt            pgtype.Timestamptz   `db:"created_at" json:"CreatedAt"`
	UpdatedAt            pgtype.Timestamptz   `db:"updated_at" json:"UpdatedAt"`
	VideoTitle           *string              `db:"video_title" json:"VideoTitle"`
	VideoPath            *string              `db:"video_path" json:"VideoPath"`
	ThumbnailPath        *string              `db:"thumbnail_path" json:"ThumbnailPath"`
	VideoDurationSeconds *int32               `db:"video_duration_seconds" json:"VideoDurationSeconds"`
	ProbeData            *videoinfo.ProbeInfo `db:"probe_data" json:"ProbeData"`
}

// GetComposeProject
//
//	SELECT cp.id, cp.video_id, cp.created_by, cp.title, cp.canvas, cp.timeline,
//	       cp.format, cp.quality, cp.created_at, cp.updated_at,
//	       v.title AS video_title, v.video_path,
//	       v.thumbnail_path, v.duration_seconds AS video_duration_seconds,
//	       v.probe_data
//	FROM compose_projects cp
//	LEFT JOIN videos v ON v.id = cp.video_id
//	WHERE cp.id = $1
func (q *Queries) GetComposeProject(ctx context.Context, id pgtype.UUID) (*GetComposeProjectRow, error) {
	row := q.db.QueryRow(ctx, getComposeProject, id)
	var i GetComposeProjectRow
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.CreatedBy,
		&i.Title,
		&i.Canvas,
		&i.Timeline,
		&i.Format,
		&i.Quality,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VideoTitle,
		&i.VideoPath,
		&i.ThumbnailPath,
		&i.VideoDurationSeconds,
		&i.ProbeData,
	)
	return &i, err
}

const getVideoForCompose = `-- name: GetVideoForCompose :one
SELECT id, title, video_path, thumbnail_path, duration_seconds, probe_data
FROM videos
WHERE id = $1
`

type GetVideoForComposeRow struct {
	ID              pgtype.UUID          `db:"id" json:"ID"`
	Title           string               `db:"title" json:"Title"`
	VideoPath       *string              `db:"video_path" json:"VideoPath"`
	ThumbnailPath   *string              `db:"thumbnail_path" json:"ThumbnailPath"`
	DurationSeconds *int32               `db:"duration_seconds" json:"DurationSeconds"`
	ProbeData       *videoinfo.ProbeInfo `db:"probe_data" json:"ProbeData"`
}

// Get video data needed for the compose editor.
//
//	SELECT id, title, video_path, thumbnail_path, duration_seconds, probe_data
//	FROM videos
//	WHERE id = $1
func (q *Queries) GetVideoForCompose(ctx context.Context, id pgtype.UUID) (*GetVideoForComposeRow, error) {
	row := q.db.QueryRow(ctx, getVideoForCompose, id)
	var i GetVideoForComposeRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.VideoPath,
		&i.ThumbnailPath,
		&i.DurationSeconds,
		&i.ProbeData,
	)
	return &i, err
}

const latestComposeJobPerProject = `-- name: LatestComposeJobPerProject :many
SELECT DISTINCT ON (project_id)
    project_id, id, status, progress_pct, file_path, created_at
FROM compose_jobs
WHERE project_id = ANY($1::uuid[])
ORDER BY project_id, created_at DESC
`

type LatestComposeJobPerProjectRow struct {
	ProjectID   pgtype.UUID        `db:"project_id" json:"ProjectID"`
	ID          pgtype.UUID        `db:"id" json:"ID"`
	Status      ExportStatus       `db:"status" json:"Status"`
	ProgressPct int32              `db:"progress_pct" json:"ProgressPct"`
	FilePath    string             `db:"file_path" json:"FilePath"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"CreatedAt"`
}

// Get the latest compose job for each project (for library cards).
//
//	SELECT DISTINCT ON (project_id)
//	    project_id, id, status, progress_pct, file_path, created_at
//	FROM compose_jobs
//	WHERE project_id = ANY($1::uuid[])
//	ORDER BY project_id, created_at DESC
func (q *Queries) LatestComposeJobPerProject(ctx context.Context, projectIds []pgtype.UUID) ([]*LatestComposeJobPerProjectRow, error) {
	rows, err := q.db.Query(ctx, latestComposeJobPerProject, projectIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*LatestComposeJobPerProjectRow
	for rows.Next() {
		var i LatestComposeJobPerProjectRow
		if err := rows.Scan(
			&i.ProjectID,
			&i.ID,
			&i.Status,
			&i.ProgressPct,
			&i.FilePath,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listComposeJobsByProject = `-- name: ListComposeJobsByProject :many
SELECT id, status, progress_pct, file_path, size_bytes, last_error,
       created_at, finished_at
FROM compose_jobs
WHERE project_id = $1
ORDER BY created_at DESC
LIMIT 20
`

type ListComposeJobsByProjectRow struct {
	ID          pgtype.UUID        `db:"id" json:"ID"`
	Status      ExportStatus       `db:"status" json:"Status"`
	ProgressPct int32              `db:"progress_pct" json:"ProgressPct"`
	FilePath    string             `db:"file_path" json:"FilePath"`
	SizeBytes   int64              `db:"size_bytes" json:"SizeBytes"`
	LastError   *string            `db:"last_error" json:"LastError"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"CreatedAt"`
	FinishedAt  pgtype.Timestamptz `db:"finished_at" json:"FinishedAt"`
}

// List all compose jobs for a project, newest first. Used to show export history.
//
//	SELECT id, status, progress_pct, file_path, size_bytes, last_error,
//	       created_at, finished_at
//	FROM compose_jobs
//	WHERE project_id = $1
//	ORDER BY created_at DESC
//	LIMIT 20
func (q *Queries) ListComposeJobsByProject(ctx context.Context, projectID pgtype.UUID) ([]*ListComposeJobsByProjectRow, error) {
	rows, err := q.db.Query(ctx, listComposeJobsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListComposeJobsByProjectRow
	for rows.Next() {
		var i ListComposeJobsByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.ProgressPct,
			&i.FilePath,
			&i.SizeBytes,
			&i.LastError,
			&i.CreatedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listComposeProjects = `-- name: ListComposeProjects :many

SELECT cp.id, cp.video_id, cp.title, cp.canvas, cp.format, cp.quality,
       cp.created_at, cp.updated_at,
       v.title AS video_title, v.thumbnail_path, v.duration_seconds AS video_duration_seconds
FROM compose_projects cp
LEFT JOIN videos v ON v.id = cp.video_id
WHERE cp.created_by = $1
ORDER BY cp.updated_at DESC
`

type ListComposeProjectsRow struct {
	ID                   pgtype.UUID        `db:"id" json:"ID"`
	VideoID              pgtype.UUID        `db:"video_id" json:"VideoID"`
	Title                string             `db:"title" json:"Title"`
	Canvas               []byte             `db:"canvas" json:"Canvas"`
	Format               string             `db:"format" json:"Format"`
	Quality              string             `db:"quality" json:"Quality"`
	CreatedAt            pgtype.Timestamptz `db:"created_at" json:"CreatedAt"`
	UpdatedAt            pgtype.Timestamptz `db:"updated_at" json:"UpdatedAt"`
	VideoTitle           *string            `db:"video_title" json:"VideoTitle"`
	ThumbnailPath        *string            `db:"thumbnail_path" json:"ThumbnailPath"`
	VideoDurationSeconds *int32             `db:"video_duration_seconds" json:"VideoDurationSeconds"`
}

// ============================================================================
// Compose projects (persistent editor state for multi-crop compositions)
// ============================================================================
// List all compose projects for a user, newest-updated first.
//
//	SELECT cp.id, cp.video_id, cp.title, cp.canvas, cp.format, cp.quality,
//	       cp.created_at, cp.updated_at,
//	       v.title AS video_title, v.thumbnail_path, v.duration_seconds AS video_duration_seconds
//	FROM compose_projects cp
//	LEFT JOIN videos v ON v.id = cp.video_id
//	WHERE cp.created_by = $1
//	ORDER BY cp.updated_at DESC
func (q *Queries) ListComposeProjects(ctx context.Context, userID pgtype.UUID) ([]*ListComposeProjectsRow, error) {
	rows, err := q.db.Query(ctx, listComposeProjects, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListComposeProjectsRow
	for rows.Next() {
		var i ListComposeProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.VideoID,
			&i.Title,
			&i.Canvas,
			&i.Format,
			&i.Quality,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VideoTitle,
			&i.ThumbnailPath,
			&i.VideoDurationSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetStuckComposeJobs = `-- name: ResetStuckComposeJobs :exec
UPDATE compose_jobs
SET status     = 'queued',
    locked_at  = NULL,
    locked_by  = NULL,
    progress_pct = 0
WHERE status = 'processing'
  AND locked_at < NOW() - INTERVAL '10 minutes'
`

// Reset compose jobs stuck in processing without recent progress.
//
//	UPDATE compose_jobs
//	SET status     = 'queued',
//	    locked_at  = NULL,
//	    locked_by  = NULL,
//	    progress_pct = 0
//	WHERE status = 'processing'
//	  AND locked_at < NOW() - INTERVAL '10 minutes'
func (q *Queries) ResetStuckComposeJobs(ctx context.Context) error {
	_, err := q.db.Exec(ctx, resetStuckComposeJobs)
	return err
}

const updateComposeJobLastAccessed = `-- name: UpdateComposeJobLastAccessed :exec
UPDATE compose_jobs
SET last_accessed_at = NOW()
WHERE id = $1
`

// UpdateComposeJobLastAccessed
//
//	UPDATE compose_jobs
//	SET last_accessed_at = NOW()
//	WHERE id = $1
func (q *Queries) UpdateComposeJobLastAccessed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateComposeJobLastAccessed, id)
	return err
}

const updateComposeJobPID = `-- name: UpdateComposeJobPID :exec
UPDATE compose_jobs
SET pid = $1
WHERE id = $2
`

type UpdateComposeJobPIDParams struct {
	Pid *int32      `db:"pid" json:"Pid"`
	ID  pgtype.UUID `db:"id" json:"ID"`
}

// UpdateComposeJobPID
//
//	UPDATE compose_jobs
//	SET pid = $1
//	WHERE id = $2
func (q *Queries) UpdateComposeJobPID(ctx context.Context, arg *UpdateComposeJobPIDParams) error {
	_, err := q.db.Exec(ctx, updateComposeJobPID, arg.Pid, arg.ID)
	return err
}

const updateComposeJobProgress = `-- name: UpdateComposeJobProgress :exec
UPDATE compose_jobs
SET progress_pct = $1
WHERE id = $2
`

type UpdateComposeJobProgressParams struct {
	ProgressPct int32       `db:"progress_pct" json:"ProgressPct"`
	ID          pgtype.UUID `db:"id" json:"ID"`
}

// UpdateComposeJobProgress
//
//	UPDATE compose_jobs
//	SET progress_pct = $1
//	WHERE id = $2
func (q *Queries) UpdateComposeJobProgress(ctx context.Context, arg *UpdateComposeJobProgressParams) error {
	_, err := q.db.Exec(ctx, updateComposeJobProgress, arg.ProgressPct, arg.ID)
	return err
}

const updateComposeProject = `-- name: UpdateComposeProject :exec
UPDATE compose_projects
SET title     = $1,
    canvas    = $2,
    timeline  = $3,
    format    = $4,
    quality   = $5,
    updated_at = NOW()
WHERE id = $6
  AND created_by = $7
`

type UpdateComposeProjectParams struct {
	Title    string      `db:"title" json:"Title"`
	Canvas   []byte      `db:"canvas" json:"Canvas"`
	Timeline []byte      `db:"timeline" json:"Timeline"`
	Format   string      `db:"format" json:"Format"`
	Quality  string      `db:"quality" json:"Quality"`
	ID       pgtype.UUID `db:"id" json:"ID"`
	UserID   pgtype.UUID `db:"user_id" json:"UserID"`
}

// UpdateComposeProject
//
//	UPDATE compose_projects
//	SET title     = $1,
//	    canvas    = $2,
//	    timeline  = $3,
//	    format    = $4,
//	    quality   = $5,
//	    updated_at = NOW()
//	WHERE id = $6
//	  AND created_by = $7
func (q *Queries) UpdateComposeProject(ctx context.Context, arg *UpdateComposeProjectParams) error {
	_, err := q.db.Exec(ctx, updateComposeProject,
		arg.Title,
		arg.Canvas,
		arg.Timeline,
		arg.Format,
		arg.Quality,
		arg.ID,
		arg.UserID,
	)
	return err
}
