// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: marker_queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMarker = `-- name: CreateMarker :one
INSERT INTO markers (
    video_id,
    timestamp,
    title,
    description,
    color,
    marker_type,
    duration,
    created_by
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
) RETURNING id, video_id, timestamp, title, description, color, marker_type, duration, created_at, created_by
`

type CreateMarkerParams struct {
	VideoID     pgtype.UUID `db:"video_id" json:"VideoID"`
	Timestamp   float64     `db:"timestamp" json:"Timestamp"`
	Title       string      `db:"title" json:"Title"`
	Description string      `db:"description" json:"Description"`
	Color       string      `db:"color" json:"Color"`
	MarkerType  MarkerType  `db:"marker_type" json:"MarkerType"`
	Duration    *float64    `db:"duration" json:"Duration"`
	CreatedBy   pgtype.UUID `db:"created_by" json:"CreatedBy"`
}

// CreateMarker
//
//	INSERT INTO markers (
//	    video_id,
//	    timestamp,
//	    title,
//	    description,
//	    color,
//	    marker_type,
//	    duration,
//	    created_by
//	) VALUES (
//	    $1,
//	    $2,
//	    $3,
//	    $4,
//	    $5,
//	    $6,
//	    $7,
//	    $8
//	) RETURNING id, video_id, timestamp, title, description, color, marker_type, duration, created_at, created_by
func (q *Queries) CreateMarker(ctx context.Context, arg *CreateMarkerParams) (*Marker, error) {
	row := q.db.QueryRow(ctx, createMarker,
		arg.VideoID,
		arg.Timestamp,
		arg.Title,
		arg.Description,
		arg.Color,
		arg.MarkerType,
		arg.Duration,
		arg.CreatedBy,
	)
	var i Marker
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.Timestamp,
		&i.Title,
		&i.Description,
		&i.Color,
		&i.MarkerType,
		&i.Duration,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return &i, err
}

const deleteMarker = `-- name: DeleteMarker :exec
DELETE FROM markers
WHERE id = $1
`

// DeleteMarker
//
//	DELETE FROM markers
//	WHERE id = $1
func (q *Queries) DeleteMarker(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMarker, id)
	return err
}

const deleteMarkersByVideo = `-- name: DeleteMarkersByVideo :exec
DELETE FROM markers
WHERE video_id = $1
`

// DeleteMarkersByVideo
//
//	DELETE FROM markers
//	WHERE video_id = $1
func (q *Queries) DeleteMarkersByVideo(ctx context.Context, videoID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMarkersByVideo, videoID)
	return err
}

const getMarker = `-- name: GetMarker :one
SELECT id, video_id, timestamp, title, description, color, marker_type, duration, created_at, created_by FROM markers
WHERE id = $1
`

// GetMarker
//
//	SELECT id, video_id, timestamp, title, description, color, marker_type, duration, created_at, created_by FROM markers
//	WHERE id = $1
func (q *Queries) GetMarker(ctx context.Context, id pgtype.UUID) (*Marker, error) {
	row := q.db.QueryRow(ctx, getMarker, id)
	var i Marker
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.Timestamp,
		&i.Title,
		&i.Description,
		&i.Color,
		&i.MarkerType,
		&i.Duration,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return &i, err
}

const listMarkersByVideo = `-- name: ListMarkersByVideo :many
SELECT id, video_id, timestamp, title, description, color, marker_type, duration, created_at, created_by FROM markers
WHERE video_id = $1
ORDER BY timestamp ASC
`

// ListMarkersByVideo
//
//	SELECT id, video_id, timestamp, title, description, color, marker_type, duration, created_at, created_by FROM markers
//	WHERE video_id = $1
//	ORDER BY timestamp ASC
func (q *Queries) ListMarkersByVideo(ctx context.Context, videoID pgtype.UUID) ([]*Marker, error) {
	rows, err := q.db.Query(ctx, listMarkersByVideo, videoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Marker
	for rows.Next() {
		var i Marker
		if err := rows.Scan(
			&i.ID,
			&i.VideoID,
			&i.Timestamp,
			&i.Title,
			&i.Description,
			&i.Color,
			&i.MarkerType,
			&i.Duration,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMarker = `-- name: UpdateMarker :one
UPDATE markers
SET
    timestamp = COALESCE($1, timestamp),
    title = COALESCE($2, title),
    description = COALESCE($3, description),
    color = COALESCE($4, color),
    marker_type = COALESCE($5, marker_type),
    duration = COALESCE($6, duration)
WHERE id = $7
RETURNING id, video_id, timestamp, title, description, color, marker_type, duration, created_at, created_by
`

type UpdateMarkerParams struct {
	Timestamp   *float64       `db:"timestamp" json:"Timestamp"`
	Title       *string        `db:"title" json:"Title"`
	Description *string        `db:"description" json:"Description"`
	Color       *string        `db:"color" json:"Color"`
	MarkerType  NullMarkerType `db:"marker_type" json:"MarkerType"`
	Duration    *float64       `db:"duration" json:"Duration"`
	ID          pgtype.UUID    `db:"id" json:"ID"`
}

// UpdateMarker
//
//	UPDATE markers
//	SET
//	    timestamp = COALESCE($1, timestamp),
//	    title = COALESCE($2, title),
//	    description = COALESCE($3, description),
//	    color = COALESCE($4, color),
//	    marker_type = COALESCE($5, marker_type),
//	    duration = COALESCE($6, duration)
//	WHERE id = $7
//	RETURNING id, video_id, timestamp, title, description, color, marker_type, duration, created_at, created_by
func (q *Queries) UpdateMarker(ctx context.Context, arg *UpdateMarkerParams) (*Marker, error) {
	row := q.db.QueryRow(ctx, updateMarker,
		arg.Timestamp,
		arg.Title,
		arg.Description,
		arg.Color,
		arg.MarkerType,
		arg.Duration,
		arg.ID,
	)
	var i Marker
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.Timestamp,
		&i.Title,
		&i.Description,
		&i.Color,
		&i.MarkerType,
		&i.Duration,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return &i, err
}
