// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: network_queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getNetworkXChannel = `-- name: GetNetworkXChannel :one
SELECT id, created_at, updated_at, platform, identity_key, channel_id, uploader, canonical_url, creator_id, search FROM channels
WHERE platform IN ('twitter','x') AND (
 lower(ltrim(identity_key,'@'))=$1
 OR lower(substring(canonical_url from '^https?://(?:www\.)?(?:x|twitter)\.com/([^/?#]+)'))=$1
)
ORDER BY created_at,id LIMIT 1
`

// GetNetworkXChannel
//
//	SELECT id, created_at, updated_at, platform, identity_key, channel_id, uploader, canonical_url, creator_id, search FROM channels
//	WHERE platform IN ('twitter','x') AND (
//	 lower(ltrim(identity_key,'@'))=$1
//	 OR lower(substring(canonical_url from '^https?://(?:www\.)?(?:x|twitter)\.com/([^/?#]+)'))=$1
//	)
//	ORDER BY created_at,id LIMIT 1
func (q *Queries) GetNetworkXChannel(ctx context.Context, handle string) (*Channel, error) {
	row := q.db.QueryRow(ctx, getNetworkXChannel, handle)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Platform,
		&i.IdentityKey,
		&i.ChannelID,
		&i.Uploader,
		&i.CanonicalURL,
		&i.CreatorID,
		&i.Search,
	)
	return &i, err
}

const listCommenterNetworkEdges = `-- name: ListCommenterNetworkEdges :many
WITH sparse AS (
  SELECT c.id FROM commenters c WHERE c.channel_id IS NOT NULL
  UNION
  SELECT w.commenter_id FROM commenter_watchlist w
  UNION
  SELECT f.commenter_id FROM osint_flags f
  WHERE f.dismissed_at IS NULL AND f.commenter_id IS NOT NULL
  UNION
  SELECT l.a_id FROM commenter_links l WHERE l.kind = 'user'
  UNION
  SELECT l.b_id FROM commenter_links l WHERE l.kind = 'user'
), edge_rows AS (
  SELECT e.id::text AS id,
         e.from_channel_id,
         e.commenter_id,
         NULL::uuid AS peer_commenter_id,
         e.kind,
         e.weight::float8 AS weight,
         COALESCE(e.evidence->>'summary', e.kind)::text AS evidence,
         e.video_id
  FROM commenter_edges e
  WHERE e.commenter_id IN (SELECT id FROM sparse)
    AND (e.kind <> 'commented_by' OR e.from_channel_id IS NOT NULL)
  UNION ALL
  SELECT ('style:' || l.a_id::text || ':' || l.b_id::text) AS id,
         NULL::uuid AS from_channel_id,
         l.a_id AS commenter_id,
         l.b_id AS peer_commenter_id,
         'style'::text AS kind,
         GREATEST(l.score, 1)::float8 AS weight,
         COALESCE(l.evidence->>'summary', 'style suggestion')::text AS evidence,
         NULL::uuid AS video_id
  FROM commenter_links l
  WHERE l.kind = 'style'
    AND l.a_id IN (SELECT id FROM sparse)
    AND l.b_id IN (SELECT id FROM sparse)
)
SELECT id, from_channel_id, commenter_id, peer_commenter_id, kind, weight, evidence, video_id
FROM edge_rows
ORDER BY weight DESC, id
LIMIT 200
`

type ListCommenterNetworkEdgesRow struct {
	ID              string      `db:"id" json:"ID"`
	FromChannelID   pgtype.UUID `db:"from_channel_id" json:"FromChannelID"`
	CommenterID     pgtype.UUID `db:"commenter_id" json:"CommenterID"`
	PeerCommenterID pgtype.UUID `db:"peer_commenter_id" json:"PeerCommenterID"`
	Kind            string      `db:"kind" json:"Kind"`
	Weight          float64     `db:"weight" json:"Weight"`
	Evidence        string      `db:"evidence" json:"Evidence"`
	VideoID         pgtype.UUID `db:"video_id" json:"VideoID"`
}

// Pre-aggregated commenter edges (strongest-N).
//
//	WITH sparse AS (
//	  SELECT c.id FROM commenters c WHERE c.channel_id IS NOT NULL
//	  UNION
//	  SELECT w.commenter_id FROM commenter_watchlist w
//	  UNION
//	  SELECT f.commenter_id FROM osint_flags f
//	  WHERE f.dismissed_at IS NULL AND f.commenter_id IS NOT NULL
//	  UNION
//	  SELECT l.a_id FROM commenter_links l WHERE l.kind = 'user'
//	  UNION
//	  SELECT l.b_id FROM commenter_links l WHERE l.kind = 'user'
//	), edge_rows AS (
//	  SELECT e.id::text AS id,
//	         e.from_channel_id,
//	         e.commenter_id,
//	         NULL::uuid AS peer_commenter_id,
//	         e.kind,
//	         e.weight::float8 AS weight,
//	         COALESCE(e.evidence->>'summary', e.kind)::text AS evidence,
//	         e.video_id
//	  FROM commenter_edges e
//	  WHERE e.commenter_id IN (SELECT id FROM sparse)
//	    AND (e.kind <> 'commented_by' OR e.from_channel_id IS NOT NULL)
//	  UNION ALL
//	  SELECT ('style:' || l.a_id::text || ':' || l.b_id::text) AS id,
//	         NULL::uuid AS from_channel_id,
//	         l.a_id AS commenter_id,
//	         l.b_id AS peer_commenter_id,
//	         'style'::text AS kind,
//	         GREATEST(l.score, 1)::float8 AS weight,
//	         COALESCE(l.evidence->>'summary', 'style suggestion')::text AS evidence,
//	         NULL::uuid AS video_id
//	  FROM commenter_links l
//	  WHERE l.kind = 'style'
//	    AND l.a_id IN (SELECT id FROM sparse)
//	    AND l.b_id IN (SELECT id FROM sparse)
//	)
//	SELECT id, from_channel_id, commenter_id, peer_commenter_id, kind, weight, evidence, video_id
//	FROM edge_rows
//	ORDER BY weight DESC, id
//	LIMIT 200
func (q *Queries) ListCommenterNetworkEdges(ctx context.Context) ([]*ListCommenterNetworkEdgesRow, error) {
	rows, err := q.db.Query(ctx, listCommenterNetworkEdges)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListCommenterNetworkEdgesRow
	for rows.Next() {
		var i ListCommenterNetworkEdgesRow
		if err := rows.Scan(
			&i.ID,
			&i.FromChannelID,
			&i.CommenterID,
			&i.PeerCommenterID,
			&i.Kind,
			&i.Weight,
			&i.Evidence,
			&i.VideoID,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommenterNetworkNodes = `-- name: ListCommenterNetworkNodes :many
WITH sparse AS (
  SELECT c.id FROM commenters c WHERE c.channel_id IS NOT NULL
  UNION
  SELECT w.commenter_id FROM commenter_watchlist w
  UNION
  SELECT f.commenter_id FROM osint_flags f
  WHERE f.dismissed_at IS NULL AND f.commenter_id IS NOT NULL
  UNION
  SELECT l.a_id FROM commenter_links l WHERE l.kind = 'user'
  UNION
  SELECT l.b_id FROM commenter_links l WHERE l.kind = 'user'
)
SELECT c.id,
       c.source,
       c.display_name,
       c.author_url,
       c.comment_count,
       c.channel_id,
       EXISTS (
         SELECT 1 FROM commenter_watchlist w
         WHERE w.commenter_id = c.id AND w.user_id = $1
       ) AS watchlisted,
       COALESCE((
         SELECT array_agg(DISTINCT f.kind ORDER BY f.kind)
         FROM osint_flags f
         WHERE f.commenter_id = c.id AND f.dismissed_at IS NULL
       ), '{}'::text[])::text[] AS open_flag_kinds
FROM commenters c
WHERE c.id IN (SELECT id FROM sparse)
ORDER BY c.comment_count DESC, c.display_name, c.id
LIMIT 200
`

type ListCommenterNetworkNodesRow struct {
	ID            pgtype.UUID `db:"id" json:"ID"`
	Source        string      `db:"source" json:"Source"`
	DisplayName   string      `db:"display_name" json:"DisplayName"`
	AuthorURL     string      `db:"author_url" json:"AuthorUrl"`
	CommentCount  int64       `db:"comment_count" json:"CommentCount"`
	ChannelID     pgtype.UUID `db:"channel_id" json:"ChannelID"`
	Watchlisted   bool        `db:"watchlisted" json:"Watchlisted"`
	OpenFlagKinds []string    `db:"open_flag_kinds" json:"OpenFlagKinds"`
}

// Sparse commenter nodes for /network (watchlisted, open flag, user link, or channel_id).
//
//	WITH sparse AS (
//	  SELECT c.id FROM commenters c WHERE c.channel_id IS NOT NULL
//	  UNION
//	  SELECT w.commenter_id FROM commenter_watchlist w
//	  UNION
//	  SELECT f.commenter_id FROM osint_flags f
//	  WHERE f.dismissed_at IS NULL AND f.commenter_id IS NOT NULL
//	  UNION
//	  SELECT l.a_id FROM commenter_links l WHERE l.kind = 'user'
//	  UNION
//	  SELECT l.b_id FROM commenter_links l WHERE l.kind = 'user'
//	)
//	SELECT c.id,
//	       c.source,
//	       c.display_name,
//	       c.author_url,
//	       c.comment_count,
//	       c.channel_id,
//	       EXISTS (
//	         SELECT 1 FROM commenter_watchlist w
//	         WHERE w.commenter_id = c.id AND w.user_id = $1
//	       ) AS watchlisted,
//	       COALESCE((
//	         SELECT array_agg(DISTINCT f.kind ORDER BY f.kind)
//	         FROM osint_flags f
//	         WHERE f.commenter_id = c.id AND f.dismissed_at IS NULL
//	       ), '{}'::text[])::text[] AS open_flag_kinds
//	FROM commenters c
//	WHERE c.id IN (SELECT id FROM sparse)
//	ORDER BY c.comment_count DESC, c.display_name, c.id
//	LIMIT 200
func (q *Queries) ListCommenterNetworkNodes(ctx context.Context, userID pgtype.UUID) ([]*ListCommenterNetworkNodesRow, error) {
	rows, err := q.db.Query(ctx, listCommenterNetworkNodes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListCommenterNetworkNodesRow
	for rows.Next() {
		var i ListCommenterNetworkNodesRow
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.DisplayName,
			&i.AuthorURL,
			&i.CommentCount,
			&i.ChannelID,
			&i.Watchlisted,
			&i.OpenFlagKinds,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNetworkChannels = `-- name: ListNetworkChannels :many
SELECT ch.id, ch.created_at, ch.updated_at, ch.platform, ch.identity_key, ch.channel_id, ch.uploader, ch.canonical_url, ch.creator_id, ch.search, COALESCE(cr.name, '')::text AS creator_name,
 (SELECT count(*) FROM videos v WHERE v.channel_row_id=ch.id)::bigint AS video_count
FROM channels ch LEFT JOIN creators cr ON cr.id=ch.creator_id
ORDER BY ch.uploader, ch.id
`

type ListNetworkChannelsRow struct {
	ID           pgtype.UUID        `db:"id" json:"ID"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"CreatedAt"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"UpdatedAt"`
	Platform     string             `db:"platform" json:"Platform"`
	IdentityKey  string             `db:"identity_key" json:"IdentityKey"`
	ChannelID    string             `db:"channel_id" json:"ChannelID"`
	Uploader     string             `db:"uploader" json:"Uploader"`
	CanonicalURL string             `db:"canonical_url" json:"CanonicalUrl"`
	CreatorID    pgtype.UUID        `db:"creator_id" json:"CreatorID"`
	Search       string             `db:"search" json:"Search"`
	CreatorName  string             `db:"creator_name" json:"CreatorName"`
	VideoCount   int64              `db:"video_count" json:"VideoCount"`
}

// ListNetworkChannels
//
//	SELECT ch.id, ch.created_at, ch.updated_at, ch.platform, ch.identity_key, ch.channel_id, ch.uploader, ch.canonical_url, ch.creator_id, ch.search, COALESCE(cr.name, '')::text AS creator_name,
//	 (SELECT count(*) FROM videos v WHERE v.channel_row_id=ch.id)::bigint AS video_count
//	FROM channels ch LEFT JOIN creators cr ON cr.id=ch.creator_id
//	ORDER BY ch.uploader, ch.id
func (q *Queries) ListNetworkChannels(ctx context.Context) ([]*ListNetworkChannelsRow, error) {
	rows, err := q.db.Query(ctx, listNetworkChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListNetworkChannelsRow
	for rows.Next() {
		var i ListNetworkChannelsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Platform,
			&i.IdentityKey,
			&i.ChannelID,
			&i.Uploader,
			&i.CanonicalURL,
			&i.CreatorID,
			&i.Search,
			&i.CreatorName,
			&i.VideoCount,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNetworkContext = `-- name: ListNetworkContext :many
WITH own_topics AS (
 SELECT DISTINCT cwt.topic_slug AS topic
 FROM context_window_topics cwt
 JOIN context_windows cw ON cw.id = cwt.window_id
 JOIN videos v ON v.id = cw.video_id
 WHERE v.channel_row_id = ANY($1::uuid[]) AND NOT cw.stale AND cw.kind = 'window'
), candidates AS (
 SELECT cw.id, cw.video_id, cw.start_ts, cw.end_ts, cw.title, cw.summary,
 cw.topics, cw.entities, v.title AS video_title, v.uploader, cw.updated_at,
 (v.channel_row_id = ANY($1::uuid[]))::boolean AS selected_channel,
 ARRAY(
   SELECT t.title FROM context_window_topics x
   JOIN topics t ON t.slug = x.topic_slug
   WHERE x.window_id = cw.id AND x.topic_slug IN (SELECT topic FROM own_topics)
 )::text[] AS shared_topics
 FROM context_windows cw JOIN videos v ON v.id = cw.video_id
 WHERE NOT cw.stale AND cw.kind = 'window'
 AND (v.channel_row_id = ANY($1::uuid[])
   OR EXISTS (
     SELECT 1 FROM context_window_topics x
     WHERE x.window_id = cw.id AND x.topic_slug IN (SELECT topic FROM own_topics)
   ))
 AND ($2::text = '' OR concat_ws(' ', cw.title, cw.summary, array_to_string(cw.topics, ' '), array_to_string(cw.entities, ' ')) ILIKE '%' || $2 || '%')
), ranked AS (
 SELECT id, video_id, start_ts, end_ts, title, summary, topics, entities, video_title, uploader, updated_at, selected_channel, shared_topics, row_number() OVER (PARTITION BY selected_channel ORDER BY cardinality(shared_topics) DESC, updated_at DESC, id) AS position
 FROM candidates WHERE selected_channel OR cardinality(shared_topics) >= 1
)
SELECT id, video_id, start_ts, end_ts, title, summary, topics, entities, video_title, uploader, selected_channel, shared_topics
FROM ranked WHERE position <= 15
ORDER BY selected_channel DESC, position
`

type ListNetworkContextParams struct {
	ChannelIds []pgtype.UUID `db:"channel_ids" json:"ChannelIds"`
	Query      string        `db:"query" json:"Query"`
}

type ListNetworkContextRow struct {
	ID              pgtype.UUID `db:"id" json:"ID"`
	VideoID         pgtype.UUID `db:"video_id" json:"VideoID"`
	StartTs         float64     `db:"start_ts" json:"StartTs"`
	EndTs           float64     `db:"end_ts" json:"EndTs"`
	Title           string      `db:"title" json:"Title"`
	Summary         string      `db:"summary" json:"Summary"`
	Topics          []string    `db:"topics" json:"Topics"`
	Entities        []string    `db:"entities" json:"Entities"`
	VideoTitle      string      `db:"video_title" json:"VideoTitle"`
	Uploader        string      `db:"uploader" json:"Uploader"`
	SelectedChannel bool        `db:"selected_channel" json:"SelectedChannel"`
	SharedTopics    []string    `db:"shared_topics" json:"SharedTopics"`
}

// ListNetworkContext
//
//	WITH own_topics AS (
//	 SELECT DISTINCT cwt.topic_slug AS topic
//	 FROM context_window_topics cwt
//	 JOIN context_windows cw ON cw.id = cwt.window_id
//	 JOIN videos v ON v.id = cw.video_id
//	 WHERE v.channel_row_id = ANY($1::uuid[]) AND NOT cw.stale AND cw.kind = 'window'
//	), candidates AS (
//	 SELECT cw.id, cw.video_id, cw.start_ts, cw.end_ts, cw.title, cw.summary,
//	 cw.topics, cw.entities, v.title AS video_title, v.uploader, cw.updated_at,
//	 (v.channel_row_id = ANY($1::uuid[]))::boolean AS selected_channel,
//	 ARRAY(
//	   SELECT t.title FROM context_window_topics x
//	   JOIN topics t ON t.slug = x.topic_slug
//	   WHERE x.window_id = cw.id AND x.topic_slug IN (SELECT topic FROM own_topics)
//	 )::text[] AS shared_topics
//	 FROM context_windows cw JOIN videos v ON v.id = cw.video_id
//	 WHERE NOT cw.stale AND cw.kind = 'window'
//	 AND (v.channel_row_id = ANY($1::uuid[])
//	   OR EXISTS (
//	     SELECT 1 FROM context_window_topics x
//	     WHERE x.window_id = cw.id AND x.topic_slug IN (SELECT topic FROM own_topics)
//	   ))
//	 AND ($2::text = '' OR concat_ws(' ', cw.title, cw.summary, array_to_string(cw.topics, ' '), array_to_string(cw.entities, ' ')) ILIKE '%' || $2 || '%')
//	), ranked AS (
//	 SELECT id, video_id, start_ts, end_ts, title, summary, topics, entities, video_title, uploader, updated_at, selected_channel, shared_topics, row_number() OVER (PARTITION BY selected_channel ORDER BY cardinality(shared_topics) DESC, updated_at DESC, id) AS position
//	 FROM candidates WHERE selected_channel OR cardinality(shared_topics) >= 1
//	)
//	SELECT id, video_id, start_ts, end_ts, title, summary, topics, entities, video_title, uploader, selected_channel, shared_topics
//	FROM ranked WHERE position <= 15
//	ORDER BY selected_channel DESC, position
func (q *Queries) ListNetworkContext(ctx context.Context, arg *ListNetworkContextParams) ([]*ListNetworkContextRow, error) {
	rows, err := q.db.Query(ctx, listNetworkContext, arg.ChannelIds, arg.Query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListNetworkContextRow
	for rows.Next() {
		var i ListNetworkContextRow
		if err := rows.Scan(
			&i.ID,
			&i.VideoID,
			&i.StartTs,
			&i.EndTs,
			&i.Title,
			&i.Summary,
			&i.Topics,
			&i.Entities,
			&i.VideoTitle,
			&i.Uploader,
			&i.SelectedChannel,
			&i.SharedTopics,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
