// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: video_transcript_queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"thirdcoast.systems/rewind/pkg/utils/language"
)

const getLibraryEvidence = `-- name: GetLibraryEvidence :many
SELECT v.id,
COALESCE((SELECT t.cues FROM video_transcripts t WHERE t.video_id=v.id AND t.search @@ to_tsquery('simple',$1) ORDER BY CASE WHEN t.lang::text='en' THEN 0 ELSE 1 END,t.lang LIMIT 1),'[]'::jsonb)::jsonb AS cues,
COALESCE((SELECT c.text FROM video_comments c WHERE c.video_id=v.id AND c.search @@ to_tsquery('simple',$1) ORDER BY c.id LIMIT 1),'')::text AS comment_text
FROM videos v WHERE v.id=ANY($2::uuid[])
`

type GetLibraryEvidenceParams struct {
	Tsquery  string        `db:"tsquery" json:"Tsquery"`
	VideoIds []pgtype.UUID `db:"video_ids" json:"VideoIds"`
}

type GetLibraryEvidenceRow struct {
	ID          pgtype.UUID `db:"id" json:"ID"`
	Cues        []byte      `db:"cues" json:"Cues"`
	CommentText string      `db:"comment_text" json:"CommentText"`
}

// GetLibraryEvidence
//
//	SELECT v.id,
//	COALESCE((SELECT t.cues FROM video_transcripts t WHERE t.video_id=v.id AND t.search @@ to_tsquery('simple',$1) ORDER BY CASE WHEN t.lang::text='en' THEN 0 ELSE 1 END,t.lang LIMIT 1),'[]'::jsonb)::jsonb AS cues,
//	COALESCE((SELECT c.text FROM video_comments c WHERE c.video_id=v.id AND c.search @@ to_tsquery('simple',$1) ORDER BY c.id LIMIT 1),'')::text AS comment_text
//	FROM videos v WHERE v.id=ANY($2::uuid[])
func (q *Queries) GetLibraryEvidence(ctx context.Context, arg *GetLibraryEvidenceParams) ([]*GetLibraryEvidenceRow, error) {
	rows, err := q.db.Query(ctx, getLibraryEvidence, arg.Tsquery, arg.VideoIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetLibraryEvidenceRow
	for rows.Next() {
		var i GetLibraryEvidenceRow
		if err := rows.Scan(&i.ID, &i.Cues, &i.CommentText); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVideoTranscript = `-- name: GetVideoTranscript :one
SELECT id, created_at, updated_at, video_id, lang, format, text, raw, search, cues, coverage FROM video_transcripts
WHERE video_id = $1
ORDER BY CASE WHEN lang::text = 'en' THEN 0 ELSE 1 END, lang
LIMIT 1
`

// GetVideoTranscript returns one transcript for a video (any language).
//
//	SELECT id, created_at, updated_at, video_id, lang, format, text, raw, search, cues, coverage FROM video_transcripts
//	WHERE video_id = $1
//	ORDER BY CASE WHEN lang::text = 'en' THEN 0 ELSE 1 END, lang
//	LIMIT 1
func (q *Queries) GetVideoTranscript(ctx context.Context, videoID pgtype.UUID) (*VideoTranscript, error) {
	row := q.db.QueryRow(ctx, getVideoTranscript, videoID)
	var i VideoTranscript
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VideoID,
		&i.Lang,
		&i.Format,
		&i.Text,
		&i.Raw,
		&i.Search,
		&i.Cues,
		&i.Coverage,
	)
	return &i, err
}

const getVideoTranscriptByLanguage = `-- name: GetVideoTranscriptByLanguage :one
SELECT id, created_at, updated_at, video_id, lang, format, text, raw, search, cues, coverage FROM video_transcripts WHERE video_id = $1 AND lang = $2
`

type GetVideoTranscriptByLanguageParams struct {
	VideoID pgtype.UUID  `db:"video_id" json:"VideoID"`
	Lang    language.Tag `db:"lang" json:"Lang"`
}

// GetVideoTranscriptByLanguage
//
//	SELECT id, created_at, updated_at, video_id, lang, format, text, raw, search, cues, coverage FROM video_transcripts WHERE video_id = $1 AND lang = $2
func (q *Queries) GetVideoTranscriptByLanguage(ctx context.Context, arg *GetVideoTranscriptByLanguageParams) (*VideoTranscript, error) {
	row := q.db.QueryRow(ctx, getVideoTranscriptByLanguage, arg.VideoID, arg.Lang)
	var i VideoTranscript
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VideoID,
		&i.Lang,
		&i.Format,
		&i.Text,
		&i.Raw,
		&i.Search,
		&i.Cues,
		&i.Coverage,
	)
	return &i, err
}

const getVideoTranscriptsBatch = `-- name: GetVideoTranscriptsBatch :many
SELECT DISTINCT ON(video_id) id, created_at, updated_at, video_id, lang, format, text, raw, search, cues, coverage FROM video_transcripts WHERE video_id=ANY($1::uuid[])
ORDER BY video_id,CASE WHEN lang::text='en' THEN 0 ELSE 1 END,lang
`

// GetVideoTranscriptsBatch
//
//	SELECT DISTINCT ON(video_id) id, created_at, updated_at, video_id, lang, format, text, raw, search, cues, coverage FROM video_transcripts WHERE video_id=ANY($1::uuid[])
//	ORDER BY video_id,CASE WHEN lang::text='en' THEN 0 ELSE 1 END,lang
func (q *Queries) GetVideoTranscriptsBatch(ctx context.Context, videoIds []pgtype.UUID) ([]*VideoTranscript, error) {
	rows, err := q.db.Query(ctx, getVideoTranscriptsBatch, videoIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*VideoTranscript
	for rows.Next() {
		var i VideoTranscript
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VideoID,
			&i.Lang,
			&i.Format,
			&i.Text,
			&i.Raw,
			&i.Search,
			&i.Cues,
			&i.Coverage,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTranscripts = `-- name: SearchTranscripts :many
SELECT vt.video_id, v.title, v.uploader, v.media, v.duration_seconds, vt.lang,
       ts_rank_cd(vt.search, to_tsquery('simple', $1)) AS rank,
       COUNT(*) OVER() AS total_video_count
FROM video_transcripts vt
JOIN videos v ON v.id = vt.video_id
LEFT JOIN channels ch ON ch.id = v.channel_row_id
WHERE $1::text <> ''
  AND vt.search @@ to_tsquery('simple', $1)
  AND ($2::uuid IS NULL OR v.id = $2)
  AND ($3::text IS NULL OR v.uploader = $3)
  AND ($4::uuid IS NULL OR ch.creator_id = $4)
  AND ($5::uuid IS NULL OR ch.id = $5)
ORDER BY rank DESC,vt.video_id,vt.lang
LIMIT $7 OFFSET $6
`

type SearchTranscriptsParams struct {
	Tsquery    string      `db:"tsquery" json:"Tsquery"`
	VideoID    pgtype.UUID `db:"video_id" json:"VideoID"`
	Uploader   *string     `db:"uploader" json:"Uploader"`
	CreatorID  pgtype.UUID `db:"creator_id" json:"CreatorID"`
	ChannelID  pgtype.UUID `db:"channel_id" json:"ChannelID"`
	PageOffset int32       `db:"page_offset" json:"PageOffset"`
	PageLimit  int32       `db:"page_limit" json:"PageLimit"`
}

type SearchTranscriptsRow struct {
	VideoID         pgtype.UUID  `db:"video_id" json:"VideoID"`
	Title           string       `db:"title" json:"Title"`
	Uploader        string       `db:"uploader" json:"Uploader"`
	Media           string       `db:"media" json:"Media"`
	DurationSeconds *int32       `db:"duration_seconds" json:"DurationSeconds"`
	Lang            language.Tag `db:"lang" json:"Lang"`
	Rank            float32      `db:"rank" json:"Rank"`
	TotalVideoCount int64        `db:"total_video_count" json:"TotalVideoCount"`
}

// SearchTranscripts finds videos whose cleaned transcript matches tsquery.
// Optional uploader restricts to one channel.
//
//	SELECT vt.video_id, v.title, v.uploader, v.media, v.duration_seconds, vt.lang,
//	       ts_rank_cd(vt.search, to_tsquery('simple', $1)) AS rank,
//	       COUNT(*) OVER() AS total_video_count
//	FROM video_transcripts vt
//	JOIN videos v ON v.id = vt.video_id
//	LEFT JOIN channels ch ON ch.id = v.channel_row_id
//	WHERE $1::text <> ''
//	  AND vt.search @@ to_tsquery('simple', $1)
//	  AND ($2::uuid IS NULL OR v.id = $2)
//	  AND ($3::text IS NULL OR v.uploader = $3)
//	  AND ($4::uuid IS NULL OR ch.creator_id = $4)
//	  AND ($5::uuid IS NULL OR ch.id = $5)
//	ORDER BY rank DESC,vt.video_id,vt.lang
//	LIMIT $7 OFFSET $6
func (q *Queries) SearchTranscripts(ctx context.Context, arg *SearchTranscriptsParams) ([]*SearchTranscriptsRow, error) {
	rows, err := q.db.Query(ctx, searchTranscripts,
		arg.Tsquery,
		arg.VideoID,
		arg.Uploader,
		arg.CreatorID,
		arg.ChannelID,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*SearchTranscriptsRow
	for rows.Next() {
		var i SearchTranscriptsRow
		if err := rows.Scan(
			&i.VideoID,
			&i.Title,
			&i.Uploader,
			&i.Media,
			&i.DurationSeconds,
			&i.Lang,
			&i.Rank,
			&i.TotalVideoCount,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertVideoTranscript = `-- name: UpsertVideoTranscript :exec
INSERT INTO video_transcripts (
    video_id,
    lang,
    format,
    text,
    search,
    raw,
    cues,
    updated_at
)
VALUES (
    $1,
    $2::language_tag,
    $3,
    $4,
    to_tsvector('simple'::regconfig, coalesce($4, '')),
    $5,
    COALESCE($6::jsonb, '[]'::jsonb),
    NOW()
)
ON CONFLICT (video_id, lang)
DO UPDATE SET
    format = EXCLUDED.format,
    text = EXCLUDED.text,
    search = EXCLUDED.search,
    raw = EXCLUDED.raw,
    cues = EXCLUDED.cues,
    coverage = NULL,
    updated_at = NOW()
`

type UpsertVideoTranscriptParams struct {
	VideoID pgtype.UUID  `db:"video_id" json:"VideoID"`
	Lang    language.Tag `db:"lang" json:"Lang"`
	Format  string       `db:"format" json:"Format"`
	Text    string       `db:"text" json:"Text"`
	Raw     string       `db:"raw" json:"Raw"`
	Cues    []byte       `db:"cues" json:"Cues"`
}

// UpsertVideoTranscript stores (or updates) a transcript for a video+lang.
//
//	INSERT INTO video_transcripts (
//	    video_id,
//	    lang,
//	    format,
//	    text,
//	    search,
//	    raw,
//	    cues,
//	    updated_at
//	)
//	VALUES (
//	    $1,
//	    $2::language_tag,
//	    $3,
//	    $4,
//	    to_tsvector('simple'::regconfig, coalesce($4, '')),
//	    $5,
//	    COALESCE($6::jsonb, '[]'::jsonb),
//	    NOW()
//	)
//	ON CONFLICT (video_id, lang)
//	DO UPDATE SET
//	    format = EXCLUDED.format,
//	    text = EXCLUDED.text,
//	    search = EXCLUDED.search,
//	    raw = EXCLUDED.raw,
//	    cues = EXCLUDED.cues,
//	    coverage = NULL,
//	    updated_at = NOW()
func (q *Queries) UpsertVideoTranscript(ctx context.Context, arg *UpsertVideoTranscriptParams) error {
	_, err := q.db.Exec(ctx, upsertVideoTranscript,
		arg.VideoID,
		arg.Lang,
		arg.Format,
		arg.Text,
		arg.Raw,
		arg.Cues,
	)
	return err
}
