// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wiki_queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteWikiLinksForPage = `-- name: DeleteWikiLinksForPage :exec
DELETE FROM wiki_links
WHERE from_tree = $1 AND from_slug = $2
`

type DeleteWikiLinksForPageParams struct {
	Tree string `db:"tree" json:"Tree"`
	Slug string `db:"slug" json:"Slug"`
}

// DeleteWikiLinksForPage
//
//	DELETE FROM wiki_links
//	WHERE from_tree = $1 AND from_slug = $2
func (q *Queries) DeleteWikiLinksForPage(ctx context.Context, arg *DeleteWikiLinksForPageParams) error {
	_, err := q.db.Exec(ctx, deleteWikiLinksForPage, arg.Tree, arg.Slug)
	return err
}

const getWikiPage = `-- name: GetWikiPage :one
SELECT tree, slug, title, body, revision, creator_id, channel_id, updated_by, updated_at FROM wiki_pages
WHERE tree = $1 AND slug = $2
`

type GetWikiPageParams struct {
	Tree string `db:"tree" json:"Tree"`
	Slug string `db:"slug" json:"Slug"`
}

// GetWikiPage
//
//	SELECT tree, slug, title, body, revision, creator_id, channel_id, updated_by, updated_at FROM wiki_pages
//	WHERE tree = $1 AND slug = $2
func (q *Queries) GetWikiPage(ctx context.Context, arg *GetWikiPageParams) (*WikiPage, error) {
	row := q.db.QueryRow(ctx, getWikiPage, arg.Tree, arg.Slug)
	var i WikiPage
	err := row.Scan(
		&i.Tree,
		&i.Slug,
		&i.Title,
		&i.Body,
		&i.Revision,
		&i.CreatorID,
		&i.ChannelID,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return &i, err
}

const getWikiRevision = `-- name: GetWikiRevision :one
SELECT id, tree, slug, revision, title, body, diff, summary, actor_kind, actor_id, user_id, session_id, client_name, client_version, token_name, created_at FROM wiki_revisions
WHERE tree = $1 AND slug = $2 AND revision = $3
`

type GetWikiRevisionParams struct {
	Tree     string `db:"tree" json:"Tree"`
	Slug     string `db:"slug" json:"Slug"`
	Revision int32  `db:"revision" json:"Revision"`
}

// GetWikiRevision
//
//	SELECT id, tree, slug, revision, title, body, diff, summary, actor_kind, actor_id, user_id, session_id, client_name, client_version, token_name, created_at FROM wiki_revisions
//	WHERE tree = $1 AND slug = $2 AND revision = $3
func (q *Queries) GetWikiRevision(ctx context.Context, arg *GetWikiRevisionParams) (*WikiRevision, error) {
	row := q.db.QueryRow(ctx, getWikiRevision, arg.Tree, arg.Slug, arg.Revision)
	var i WikiRevision
	err := row.Scan(
		&i.ID,
		&i.Tree,
		&i.Slug,
		&i.Revision,
		&i.Title,
		&i.Body,
		&i.Diff,
		&i.Summary,
		&i.ActorKind,
		&i.ActorID,
		&i.UserID,
		&i.SessionID,
		&i.ClientName,
		&i.ClientVersion,
		&i.TokenName,
		&i.CreatedAt,
	)
	return &i, err
}

const insertWikiLink = `-- name: InsertWikiLink :exec
INSERT INTO wiki_links (from_tree, from_slug, to_tree, to_slug)
VALUES ($1, $2, $3, $4)
ON CONFLICT DO NOTHING
`

type InsertWikiLinkParams struct {
	FromTree string `db:"from_tree" json:"FromTree"`
	FromSlug string `db:"from_slug" json:"FromSlug"`
	ToTree   string `db:"to_tree" json:"ToTree"`
	ToSlug   string `db:"to_slug" json:"ToSlug"`
}

// InsertWikiLink
//
//	INSERT INTO wiki_links (from_tree, from_slug, to_tree, to_slug)
//	VALUES ($1, $2, $3, $4)
//	ON CONFLICT DO NOTHING
func (q *Queries) InsertWikiLink(ctx context.Context, arg *InsertWikiLinkParams) error {
	_, err := q.db.Exec(ctx, insertWikiLink,
		arg.FromTree,
		arg.FromSlug,
		arg.ToTree,
		arg.ToSlug,
	)
	return err
}

const insertWikiPage = `-- name: InsertWikiPage :one
INSERT INTO wiki_pages (
    tree, slug, title, body, revision, creator_id, channel_id, updated_by
) VALUES (
    $1,
    $2,
    $3,
    $4,
    1,
    $5,
    $6,
    $7
)
RETURNING tree, slug, title, body, revision, creator_id, channel_id, updated_by, updated_at
`

type InsertWikiPageParams struct {
	Tree      string      `db:"tree" json:"Tree"`
	Slug      string      `db:"slug" json:"Slug"`
	Title     string      `db:"title" json:"Title"`
	Body      string      `db:"body" json:"Body"`
	CreatorID pgtype.UUID `db:"creator_id" json:"CreatorID"`
	ChannelID pgtype.UUID `db:"channel_id" json:"ChannelID"`
	UpdatedBy string      `db:"updated_by" json:"UpdatedBy"`
}

// InsertWikiPage
//
//	INSERT INTO wiki_pages (
//	    tree, slug, title, body, revision, creator_id, channel_id, updated_by
//	) VALUES (
//	    $1,
//	    $2,
//	    $3,
//	    $4,
//	    1,
//	    $5,
//	    $6,
//	    $7
//	)
//	RETURNING tree, slug, title, body, revision, creator_id, channel_id, updated_by, updated_at
func (q *Queries) InsertWikiPage(ctx context.Context, arg *InsertWikiPageParams) (*WikiPage, error) {
	row := q.db.QueryRow(ctx, insertWikiPage,
		arg.Tree,
		arg.Slug,
		arg.Title,
		arg.Body,
		arg.CreatorID,
		arg.ChannelID,
		arg.UpdatedBy,
	)
	var i WikiPage
	err := row.Scan(
		&i.Tree,
		&i.Slug,
		&i.Title,
		&i.Body,
		&i.Revision,
		&i.CreatorID,
		&i.ChannelID,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return &i, err
}

const insertWikiRevision = `-- name: InsertWikiRevision :one
INSERT INTO wiki_revisions (
    tree, slug, revision, title, body, diff, summary,
    actor_kind, actor_id, user_id, session_id,
    client_name, client_version, token_name
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14
)
RETURNING id, tree, slug, revision, title, body, diff, summary, actor_kind, actor_id, user_id, session_id, client_name, client_version, token_name, created_at
`

type InsertWikiRevisionParams struct {
	Tree          string      `db:"tree" json:"Tree"`
	Slug          string      `db:"slug" json:"Slug"`
	Revision      int32       `db:"revision" json:"Revision"`
	Title         string      `db:"title" json:"Title"`
	Body          string      `db:"body" json:"Body"`
	Diff          string      `db:"diff" json:"Diff"`
	Summary       string      `db:"summary" json:"Summary"`
	ActorKind     string      `db:"actor_kind" json:"ActorKind"`
	ActorID       string      `db:"actor_id" json:"ActorID"`
	UserID        pgtype.UUID `db:"user_id" json:"UserID"`
	SessionID     string      `db:"session_id" json:"SessionID"`
	ClientName    string      `db:"client_name" json:"ClientName"`
	ClientVersion string      `db:"client_version" json:"ClientVersion"`
	TokenName     string      `db:"token_name" json:"TokenName"`
}

// InsertWikiRevision
//
//	INSERT INTO wiki_revisions (
//	    tree, slug, revision, title, body, diff, summary,
//	    actor_kind, actor_id, user_id, session_id,
//	    client_name, client_version, token_name
//	) VALUES (
//	    $1,
//	    $2,
//	    $3,
//	    $4,
//	    $5,
//	    $6,
//	    $7,
//	    $8,
//	    $9,
//	    $10,
//	    $11,
//	    $12,
//	    $13,
//	    $14
//	)
//	RETURNING id, tree, slug, revision, title, body, diff, summary, actor_kind, actor_id, user_id, session_id, client_name, client_version, token_name, created_at
func (q *Queries) InsertWikiRevision(ctx context.Context, arg *InsertWikiRevisionParams) (*WikiRevision, error) {
	row := q.db.QueryRow(ctx, insertWikiRevision,
		arg.Tree,
		arg.Slug,
		arg.Revision,
		arg.Title,
		arg.Body,
		arg.Diff,
		arg.Summary,
		arg.ActorKind,
		arg.ActorID,
		arg.UserID,
		arg.SessionID,
		arg.ClientName,
		arg.ClientVersion,
		arg.TokenName,
	)
	var i WikiRevision
	err := row.Scan(
		&i.ID,
		&i.Tree,
		&i.Slug,
		&i.Revision,
		&i.Title,
		&i.Body,
		&i.Diff,
		&i.Summary,
		&i.ActorKind,
		&i.ActorID,
		&i.UserID,
		&i.SessionID,
		&i.ClientName,
		&i.ClientVersion,
		&i.TokenName,
		&i.CreatedAt,
	)
	return &i, err
}

const listWikiBacklinks = `-- name: ListWikiBacklinks :many
SELECT p.tree, p.slug, p.title, p.revision, p.updated_at
FROM wiki_links l
JOIN wiki_pages p ON p.tree = l.from_tree AND p.slug = l.from_slug
WHERE l.to_tree = $1 AND l.to_slug = $2
ORDER BY p.tree, p.slug
`

type ListWikiBacklinksParams struct {
	Tree string `db:"tree" json:"Tree"`
	Slug string `db:"slug" json:"Slug"`
}

type ListWikiBacklinksRow struct {
	Tree      string             `db:"tree" json:"Tree"`
	Slug      string             `db:"slug" json:"Slug"`
	Title     string             `db:"title" json:"Title"`
	Revision  int32              `db:"revision" json:"Revision"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"UpdatedAt"`
}

// ListWikiBacklinks
//
//	SELECT p.tree, p.slug, p.title, p.revision, p.updated_at
//	FROM wiki_links l
//	JOIN wiki_pages p ON p.tree = l.from_tree AND p.slug = l.from_slug
//	WHERE l.to_tree = $1 AND l.to_slug = $2
//	ORDER BY p.tree, p.slug
func (q *Queries) ListWikiBacklinks(ctx context.Context, arg *ListWikiBacklinksParams) ([]*ListWikiBacklinksRow, error) {
	rows, err := q.db.Query(ctx, listWikiBacklinks, arg.Tree, arg.Slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListWikiBacklinksRow
	for rows.Next() {
		var i ListWikiBacklinksRow
		if err := rows.Scan(
			&i.Tree,
			&i.Slug,
			&i.Title,
			&i.Revision,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWikiLinks = `-- name: ListWikiLinks :many
SELECT from_tree, from_slug, to_tree, to_slug
FROM wiki_links
ORDER BY from_tree, from_slug, to_tree, to_slug
`

// ListWikiLinks
//
//	SELECT from_tree, from_slug, to_tree, to_slug
//	FROM wiki_links
//	ORDER BY from_tree, from_slug, to_tree, to_slug
func (q *Queries) ListWikiLinks(ctx context.Context) ([]*WikiLink, error) {
	rows, err := q.db.Query(ctx, listWikiLinks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*WikiLink
	for rows.Next() {
		var i WikiLink
		if err := rows.Scan(
			&i.FromTree,
			&i.FromSlug,
			&i.ToTree,
			&i.ToSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWikiLinksFromPage = `-- name: ListWikiLinksFromPage :many
SELECT to_tree, to_slug
FROM wiki_links
WHERE from_tree = $1 AND from_slug = $2
ORDER BY to_tree, to_slug
`

type ListWikiLinksFromPageParams struct {
	Tree string `db:"tree" json:"Tree"`
	Slug string `db:"slug" json:"Slug"`
}

type ListWikiLinksFromPageRow struct {
	ToTree string `db:"to_tree" json:"ToTree"`
	ToSlug string `db:"to_slug" json:"ToSlug"`
}

// ListWikiLinksFromPage
//
//	SELECT to_tree, to_slug
//	FROM wiki_links
//	WHERE from_tree = $1 AND from_slug = $2
//	ORDER BY to_tree, to_slug
func (q *Queries) ListWikiLinksFromPage(ctx context.Context, arg *ListWikiLinksFromPageParams) ([]*ListWikiLinksFromPageRow, error) {
	rows, err := q.db.Query(ctx, listWikiLinksFromPage, arg.Tree, arg.Slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListWikiLinksFromPageRow
	for rows.Next() {
		var i ListWikiLinksFromPageRow
		if err := rows.Scan(&i.ToTree, &i.ToSlug); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWikiPages = `-- name: ListWikiPages :many
SELECT tree, slug, title, body, revision, creator_id, channel_id, updated_by, updated_at FROM wiki_pages
WHERE ($1::text = '' OR tree = $1)
ORDER BY tree, slug
`

// ListWikiPages
//
//	SELECT tree, slug, title, body, revision, creator_id, channel_id, updated_by, updated_at FROM wiki_pages
//	WHERE ($1::text = '' OR tree = $1)
//	ORDER BY tree, slug
func (q *Queries) ListWikiPages(ctx context.Context, tree string) ([]*WikiPage, error) {
	rows, err := q.db.Query(ctx, listWikiPages, tree)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*WikiPage
	for rows.Next() {
		var i WikiPage
		if err := rows.Scan(
			&i.Tree,
			&i.Slug,
			&i.Title,
			&i.Body,
			&i.Revision,
			&i.CreatorID,
			&i.ChannelID,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWikiPagesForChannel = `-- name: ListWikiPagesForChannel :many
SELECT tree, slug, title, body, revision, creator_id, channel_id, updated_by, updated_at FROM wiki_pages
WHERE channel_id = $1
ORDER BY tree, slug
`

// ListWikiPagesForChannel
//
//	SELECT tree, slug, title, body, revision, creator_id, channel_id, updated_by, updated_at FROM wiki_pages
//	WHERE channel_id = $1
//	ORDER BY tree, slug
func (q *Queries) ListWikiPagesForChannel(ctx context.Context, channelID pgtype.UUID) ([]*WikiPage, error) {
	rows, err := q.db.Query(ctx, listWikiPagesForChannel, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*WikiPage
	for rows.Next() {
		var i WikiPage
		if err := rows.Scan(
			&i.Tree,
			&i.Slug,
			&i.Title,
			&i.Body,
			&i.Revision,
			&i.CreatorID,
			&i.ChannelID,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWikiPagesForCreator = `-- name: ListWikiPagesForCreator :many
SELECT tree, slug, title, body, revision, creator_id, channel_id, updated_by, updated_at FROM wiki_pages
WHERE creator_id = $1
ORDER BY tree, slug
`

// ListWikiPagesForCreator
//
//	SELECT tree, slug, title, body, revision, creator_id, channel_id, updated_by, updated_at FROM wiki_pages
//	WHERE creator_id = $1
//	ORDER BY tree, slug
func (q *Queries) ListWikiPagesForCreator(ctx context.Context, creatorID pgtype.UUID) ([]*WikiPage, error) {
	rows, err := q.db.Query(ctx, listWikiPagesForCreator, creatorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*WikiPage
	for rows.Next() {
		var i WikiPage
		if err := rows.Scan(
			&i.Tree,
			&i.Slug,
			&i.Title,
			&i.Body,
			&i.Revision,
			&i.CreatorID,
			&i.ChannelID,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWikiRevisions = `-- name: ListWikiRevisions :many
SELECT id, tree, slug, revision, title, body, diff, summary, actor_kind, actor_id, user_id, session_id, client_name, client_version, token_name, created_at FROM wiki_revisions
WHERE tree = $1 AND slug = $2
ORDER BY revision DESC
`

type ListWikiRevisionsParams struct {
	Tree string `db:"tree" json:"Tree"`
	Slug string `db:"slug" json:"Slug"`
}

// ListWikiRevisions
//
//	SELECT id, tree, slug, revision, title, body, diff, summary, actor_kind, actor_id, user_id, session_id, client_name, client_version, token_name, created_at FROM wiki_revisions
//	WHERE tree = $1 AND slug = $2
//	ORDER BY revision DESC
func (q *Queries) ListWikiRevisions(ctx context.Context, arg *ListWikiRevisionsParams) ([]*WikiRevision, error) {
	rows, err := q.db.Query(ctx, listWikiRevisions, arg.Tree, arg.Slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*WikiRevision
	for rows.Next() {
		var i WikiRevision
		if err := rows.Scan(
			&i.ID,
			&i.Tree,
			&i.Slug,
			&i.Revision,
			&i.Title,
			&i.Body,
			&i.Diff,
			&i.Summary,
			&i.ActorKind,
			&i.ActorID,
			&i.UserID,
			&i.SessionID,
			&i.ClientName,
			&i.ClientVersion,
			&i.TokenName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchWikiPages = `-- name: SearchWikiPages :many
SELECT p.tree, p.slug, p.title, p.body, p.revision, p.creator_id, p.channel_id, p.updated_by, p.updated_at,
       ts_rank(s.search, websearch_to_tsquery('simple', $1))::float8 AS rank
FROM wiki_pages p
JOIN wiki_search s ON s.tree = p.tree AND s.slug = p.slug
WHERE s.search @@ websearch_to_tsquery('simple', $1)
  AND ($2::text = '' OR p.tree = $2)
ORDER BY rank DESC, p.updated_at DESC
LIMIT $3
`

type SearchWikiPagesParams struct {
	Query     string `db:"query" json:"Query"`
	Tree      string `db:"tree" json:"Tree"`
	PageLimit int32  `db:"page_limit" json:"PageLimit"`
}

type SearchWikiPagesRow struct {
	Tree      string             `db:"tree" json:"Tree"`
	Slug      string             `db:"slug" json:"Slug"`
	Title     string             `db:"title" json:"Title"`
	Body      string             `db:"body" json:"Body"`
	Revision  int32              `db:"revision" json:"Revision"`
	CreatorID pgtype.UUID        `db:"creator_id" json:"CreatorID"`
	ChannelID pgtype.UUID        `db:"channel_id" json:"ChannelID"`
	UpdatedBy string             `db:"updated_by" json:"UpdatedBy"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"UpdatedAt"`
	Rank      float64            `db:"rank" json:"Rank"`
}

// SearchWikiPages
//
//	SELECT p.tree, p.slug, p.title, p.body, p.revision, p.creator_id, p.channel_id, p.updated_by, p.updated_at,
//	       ts_rank(s.search, websearch_to_tsquery('simple', $1))::float8 AS rank
//	FROM wiki_pages p
//	JOIN wiki_search s ON s.tree = p.tree AND s.slug = p.slug
//	WHERE s.search @@ websearch_to_tsquery('simple', $1)
//	  AND ($2::text = '' OR p.tree = $2)
//	ORDER BY rank DESC, p.updated_at DESC
//	LIMIT $3
func (q *Queries) SearchWikiPages(ctx context.Context, arg *SearchWikiPagesParams) ([]*SearchWikiPagesRow, error) {
	rows, err := q.db.Query(ctx, searchWikiPages, arg.Query, arg.Tree, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*SearchWikiPagesRow
	for rows.Next() {
		var i SearchWikiPagesRow
		if err := rows.Scan(
			&i.Tree,
			&i.Slug,
			&i.Title,
			&i.Body,
			&i.Revision,
			&i.CreatorID,
			&i.ChannelID,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWikiPage = `-- name: UpdateWikiPage :one
UPDATE wiki_pages
SET title = $1,
    body = $2,
    revision = revision + 1,
    creator_id = $3,
    channel_id = $4,
    updated_by = $5,
    updated_at = NOW()
WHERE tree = $6
  AND slug = $7
  AND revision = $8
RETURNING tree, slug, title, body, revision, creator_id, channel_id, updated_by, updated_at
`

type UpdateWikiPageParams struct {
	Title            string      `db:"title" json:"Title"`
	Body             string      `db:"body" json:"Body"`
	CreatorID        pgtype.UUID `db:"creator_id" json:"CreatorID"`
	ChannelID        pgtype.UUID `db:"channel_id" json:"ChannelID"`
	UpdatedBy        string      `db:"updated_by" json:"UpdatedBy"`
	Tree             string      `db:"tree" json:"Tree"`
	Slug             string      `db:"slug" json:"Slug"`
	ExpectedRevision int32       `db:"expected_revision" json:"ExpectedRevision"`
}

// UpdateWikiPage
//
//	UPDATE wiki_pages
//	SET title = $1,
//	    body = $2,
//	    revision = revision + 1,
//	    creator_id = $3,
//	    channel_id = $4,
//	    updated_by = $5,
//	    updated_at = NOW()
//	WHERE tree = $6
//	  AND slug = $7
//	  AND revision = $8
//	RETURNING tree, slug, title, body, revision, creator_id, channel_id, updated_by, updated_at
func (q *Queries) UpdateWikiPage(ctx context.Context, arg *UpdateWikiPageParams) (*WikiPage, error) {
	row := q.db.QueryRow(ctx, updateWikiPage,
		arg.Title,
		arg.Body,
		arg.CreatorID,
		arg.ChannelID,
		arg.UpdatedBy,
		arg.Tree,
		arg.Slug,
		arg.ExpectedRevision,
	)
	var i WikiPage
	err := row.Scan(
		&i.Tree,
		&i.Slug,
		&i.Title,
		&i.Body,
		&i.Revision,
		&i.CreatorID,
		&i.ChannelID,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return &i, err
}
